import type { SubjectQuestionBank } from "../../../shared/questionTypes";

export const computerScience: SubjectQuestionBank = {
  subject: "Computer Science",
  grades: {
    "8-9": [
      {
        question: "What does CPU stand for in computer terminology?",
        questionType: "multiple_choice",
        options: ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Computer Processing Unit"],
        correctAnswer: "Central Processing Unit",
        explanation: "CPU stands for Central Processing Unit, the brain of the computer",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Computer Basics - Hardware",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "Which of these is an example of an input device?",
        questionType: "multiple_choice",
        options: ["Keyboard", "Monitor", "Printer", "Speaker"],
        correctAnswer: "Keyboard",
        explanation: "A keyboard is an input device used to enter data into a computer",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Computer Basics - Input/Output",
        difficulty: "easy",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What is the primary purpose of an operating system?",
        questionType: "multiple_choice",
        options: ["To manage computer hardware and software resources", "To browse the internet", "To create documents", "To play games"],
        correctAnswer: "To manage computer hardware and software resources",
        explanation: "An operating system manages hardware and software, providing services for computer programs",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Software - Operating Systems",
        difficulty: "easy",
        cognitiveLevel: "comprehension"
      },
      {
        question: "In programming, what is a 'variable'?",
        questionType: "multiple_choice",
        options: ["A named storage location that holds data", "A type of loop", "A function", "An error"],
        correctAnswer: "A named storage location that holds data",
        explanation: "A variable is a container that stores data values that can change during program execution",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Programming - Basic Concepts",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What does HTML stand for?",
        questionType: "multiple_choice",
        options: ["HyperText Markup Language", "High Tech Modern Language", "Home Tool Markup Language", "Hyperlinks and Text Markup Language"],
        correctAnswer: "HyperText Markup Language",
        explanation: "HTML stands for HyperText Markup Language, used to create web pages",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Web Development - HTML",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is the correct order of problem-solving steps in computational thinking?",
        questionType: "multiple_choice",
        options: ["Understand, Plan, Execute, Review", "Execute, Plan, Review, Understand", "Plan, Execute, Understand, Review", "Review, Understand, Plan, Execute"],
        correctAnswer: "Understand, Plan, Execute, Review",
        explanation: "The problem-solving cycle involves understanding the problem, planning a solution, executing it, and reviewing the results",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Computational Thinking - Problem Solving",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What is the purpose of RAM in a computer?",
        questionType: "multiple_choice",
        options: ["Temporary storage for running programs and data", "Permanent storage for files", "Processing calculations", "Displaying graphics"],
        correctAnswer: "Temporary storage for running programs and data",
        explanation: "RAM (Random Access Memory) temporarily stores data and programs currently in use. It's volatile memory that clears when powered off",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Computer Basics - Memory",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "Which programming language is known for creating web pages?",
        questionType: "multiple_choice",
        options: ["JavaScript", "Python", "C++", "Java"],
        correctAnswer: "JavaScript",
        explanation: "JavaScript is the primary programming language for creating interactive web pages and web applications",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Programming - Languages",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What does 'www' stand for in a website URL?",
        questionType: "multiple_choice",
        options: ["World Wide Web", "World Web Wide", "Web World Wide", "Wide World Web"],
        correctAnswer: "World Wide Web",
        explanation: "WWW stands for World Wide Web, the system of interconnected webpages accessible via the internet",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Internet - Basics",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is a 'bug' in programming?",
        questionType: "multiple_choice",
        options: ["An error or flaw in code", "A type of virus", "A programming language", "A computer component"],
        correctAnswer: "An error or flaw in code",
        explanation: "A bug is an error, flaw, or unintended behavior in a program that produces incorrect results",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Programming - Debugging",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "Which of these is NOT a web browser?",
        questionType: "multiple_choice",
        options: ["Microsoft Word", "Google Chrome", "Mozilla Firefox", "Safari"],
        correctAnswer: "Microsoft Word",
        explanation: "Microsoft Word is a word processing application, not a web browser",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Software - Applications",
        difficulty: "easy",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What is the binary number system based on?",
        questionType: "multiple_choice",
        options: ["0 and 1", "0 to 9", "A to Z", "1 to 10"],
        correctAnswer: "0 and 1",
        explanation: "Binary is a base-2 number system using only two digits: 0 and 1",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Computer Basics - Number Systems",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is 'phishing' in cybersecurity?",
        questionType: "multiple_choice",
        options: ["Attempting to steal personal information through fake emails or websites", "Catching computer viruses", "Fishing for data in databases", "Searching for files"],
        correctAnswer: "Attempting to steal personal information through fake emails or websites",
        explanation: "Phishing is a cyber attack where attackers impersonate legitimate organizations to steal sensitive information",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Cybersecurity - Threats",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What is an algorithm?",
        questionType: "multiple_choice",
        options: ["A step-by-step procedure to solve a problem", "A programming language", "A type of computer", "An error message"],
        correctAnswer: "A step-by-step procedure to solve a problem",
        explanation: "An algorithm is a finite sequence of well-defined instructions to solve a problem or perform a task",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Computational Thinking - Algorithms",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "Which storage device has the largest typical capacity?",
        questionType: "multiple_choice",
        options: ["Hard Drive", "USB Flash Drive", "CD-ROM", "Floppy Disk"],
        correctAnswer: "Hard Drive",
        explanation: "Hard drives typically have the largest storage capacity, ranging from hundreds of GB to several TB",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Computer Basics - Storage",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What does 'IF-THEN-ELSE' represent in programming?",
        questionType: "multiple_choice",
        options: ["A conditional statement", "A loop", "A variable", "A function"],
        correctAnswer: "A conditional statement",
        explanation: "IF-THEN-ELSE is a conditional statement that executes different code based on whether a condition is true or false",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Programming - Control Structures",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What is cloud computing?",
        questionType: "multiple_choice",
        options: ["Storing and accessing data over the internet", "Computing during cloudy weather", "A type of computer monitor", "Local storage on your device"],
        correctAnswer: "Storing and accessing data over the internet",
        explanation: "Cloud computing means storing and accessing data and programs over the internet instead of on local computers",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Internet - Cloud Services",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "Which practice is MOST important for creating a strong password?",
        questionType: "multiple_choice",
        options: ["Using a mix of letters, numbers, and symbols", "Using your name", "Using the same password everywhere", "Using only numbers"],
        correctAnswer: "Using a mix of letters, numbers, and symbols",
        explanation: "Strong passwords combine uppercase and lowercase letters, numbers, and special characters to resist cracking",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Cybersecurity - Best Practices",
        difficulty: "easy",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What happens when you 'debug' a program?",
        questionType: "multiple_choice",
        options: ["You find and fix errors in the code", "You delete the program", "You make it run faster", "You encrypt the data"],
        correctAnswer: "You find and fix errors in the code",
        explanation: "Debugging is the process of identifying, analyzing, and removing errors or bugs from computer programs",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Programming - Testing",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "Why is it important to regularly update software and operating systems?",
        questionType: "multiple_choice",
        options: ["To fix security vulnerabilities and improve performance", "To make the computer slower", "To delete all files", "To change the color scheme"],
        correctAnswer: "To fix security vulnerabilities and improve performance",
        explanation: "Software updates patch security holes, fix bugs, and often improve performance and add new features",
        subject: "Computer Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Cybersecurity - Maintenance",
        difficulty: "hard",
        cognitiveLevel: "analysis"
      }
    ],
    "10-12": [
      {
        question: "What is the time complexity of binary search algorithm?",
        questionType: "multiple_choice",
        options: ["O(log n)", "O(n)", "O(n²)", "O(1)"],
        correctAnswer: "O(log n)",
        explanation: "Binary search has logarithmic time complexity O(log n) because it divides the search space in half each iteration",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Algorithms - Searching",
        difficulty: "medium",
        cognitiveLevel: "knowledge"
      },
      {
        question: "In object-oriented programming, what is encapsulation?",
        questionType: "multiple_choice",
        options: ["Bundling data and methods that operate on that data within a single unit", "Inheriting properties from parent class", "Using multiple forms of a method", "Creating objects from classes"],
        correctAnswer: "Bundling data and methods that operate on that data within a single unit",
        explanation: "Encapsulation is the concept of bundling data and methods together and restricting access to internal details",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Programming - OOP Concepts",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What does AI stand for, and what is its primary goal in UAE Vision 2071?",
        questionType: "multiple_choice",
        options: ["Artificial Intelligence - to achieve 100% AI reliance in government by 2031", "Automated Integration - to automate all industries", "Advanced Innovation - to lead in innovation", "Artificial Integration - to integrate all systems"],
        correctAnswer: "Artificial Intelligence - to achieve 100% AI reliance in government by 2031",
        explanation: "UAE aims for 100% AI-powered government services by 2031 as part of Vision 2071",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "AI - UAE National Strategy",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is the difference between a stack and a queue data structure?",
        questionType: "multiple_choice",
        options: ["Stack is LIFO, Queue is FIFO", "Stack is FIFO, Queue is LIFO", "Both are LIFO", "Both are FIFO"],
        correctAnswer: "Stack is LIFO, Queue is FIFO",
        explanation: "Stack follows Last-In-First-Out (LIFO) principle, while Queue follows First-In-First-Out (FIFO)",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Data Structures - Stack and Queue",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "In databases, what does SQL stand for?",
        questionType: "multiple_choice",
        options: ["Structured Query Language", "Simple Question Language", "Standard Query Logic", "System Query Language"],
        correctAnswer: "Structured Query Language",
        explanation: "SQL stands for Structured Query Language, used to manage and query databases",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Databases - SQL",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is machine learning?",
        questionType: "multiple_choice",
        options: ["Computers learning from data without explicit programming", "Machines that learn to walk", "Programming robots", "Teaching computers basic math"],
        correctAnswer: "Computers learning from data without explicit programming",
        explanation: "Machine learning is a subset of AI where systems learn from data and improve performance without being explicitly programmed",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "AI - Machine Learning",
        difficulty: "easy",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What is the main advantage of using functions in programming?",
        questionType: "multiple_choice",
        options: ["Code reusability and modularity", "Slower execution", "More memory usage", "Harder to debug"],
        correctAnswer: "Code reusability and modularity",
        explanation: "Functions allow code to be reused, make programs modular, easier to maintain, and reduce redundancy",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Programming - Functions",
        difficulty: "easy",
        cognitiveLevel: "comprehension"
      },
      {
        question: "In networking, what does 'IP' stand for?",
        questionType: "multiple_choice",
        options: ["Internet Protocol", "Internal Program", "Information Processing", "Internet Provider"],
        correctAnswer: "Internet Protocol",
        explanation: "IP (Internet Protocol) is the set of rules governing how data is sent across networks",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Networking - Protocols",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is the purpose of version control systems like Git?",
        questionType: "multiple_choice",
        options: ["Track changes in code and enable collaboration", "Compile programs", "Test software", "Design user interfaces"],
        correctAnswer: "Track changes in code and enable collaboration",
        explanation: "Version control systems track code changes, enable collaboration, and allow reverting to previous versions",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Software Development - Version Control",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What is polymorphism in object-oriented programming?",
        questionType: "multiple_choice",
        options: ["The ability of different objects to respond to the same method in different ways", "Creating multiple objects", "Using many variables", "Having multiple files"],
        correctAnswer: "The ability of different objects to respond to the same method in different ways",
        explanation: "Polymorphism allows objects of different types to be treated uniformly while responding differently to the same method call",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Programming - OOP Concepts",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "Which sorting algorithm has the best average-case time complexity?",
        questionType: "multiple_choice",
        options: ["Merge Sort O(n log n)", "Bubble Sort O(n²)", "Selection Sort O(n²)", "Insertion Sort O(n²)"],
        correctAnswer: "Merge Sort O(n log n)",
        explanation: "Merge Sort has O(n log n) time complexity in all cases, making it more efficient than quadratic algorithms for large datasets",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Algorithms - Sorting",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What is blockchain technology primarily used for?",
        questionType: "multiple_choice",
        options: ["Creating secure, decentralized digital ledgers", "Blocking websites", "Storing passwords", "Encrypting emails"],
        correctAnswer: "Creating secure, decentralized digital ledgers",
        explanation: "Blockchain is a distributed ledger technology that creates secure, transparent, and tamper-resistant records",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Emerging Technologies - Blockchain",
        difficulty: "medium",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is the purpose of an API (Application Programming Interface)?",
        questionType: "multiple_choice",
        options: ["To allow different software applications to communicate", "To create user interfaces", "To debug programs", "To store data"],
        correctAnswer: "To allow different software applications to communicate",
        explanation: "APIs define how software components should interact, enabling different applications to communicate and share data",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Software Development - APIs",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "In cybersecurity, what is 'encryption'?",
        questionType: "multiple_choice",
        options: ["Converting data into coded form to prevent unauthorized access", "Deleting data", "Copying data", "Compressing data"],
        correctAnswer: "Converting data into coded form to prevent unauthorized access",
        explanation: "Encryption converts plain text into cipher text using algorithms, protecting data from unauthorized access",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Cybersecurity - Encryption",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is the Internet of Things (IoT)?",
        questionType: "multiple_choice",
        options: ["Network of physical devices connected and exchanging data", "Collection of websites", "Social media platforms", "Cloud storage systems"],
        correctAnswer: "Network of physical devices connected and exchanging data",
        explanation: "IoT refers to the interconnected network of physical devices that collect and exchange data over the internet",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Emerging Technologies - IoT",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is Big Data?",
        questionType: "multiple_choice",
        options: ["Extremely large datasets that require specialized tools to process", "Data stored on large hard drives", "Long text files", "High-resolution images"],
        correctAnswer: "Extremely large datasets that require specialized tools to process",
        explanation: "Big Data refers to datasets so large and complex that traditional data processing tools cannot handle them effectively",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Data Science - Big Data",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "Which data structure is best suited for implementing a browser's back button?",
        questionType: "multiple_choice",
        options: ["Stack", "Queue", "Array", "Tree"],
        correctAnswer: "Stack",
        explanation: "A stack's LIFO (Last-In-First-Out) property makes it ideal for tracking browsing history for the back button",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Data Structures - Applications",
        difficulty: "hard",
        cognitiveLevel: "application"
      },
      {
        question: "What is the difference between compilers and interpreters?",
        questionType: "multiple_choice",
        options: ["Compilers translate entire program at once; interpreters translate line by line", "They are the same thing", "Interpreters are faster", "Compilers only work with Java"],
        correctAnswer: "Compilers translate entire program at once; interpreters translate line by line",
        explanation: "Compilers convert the entire source code to machine code before execution, while interpreters translate and execute line by line",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Programming - Language Processing",
        difficulty: "hard",
        cognitiveLevel: "analysis"
      },
      {
        question: "In the context of UAE's digital transformation, what is the significance of smart cities?",
        questionType: "multiple_choice",
        options: ["Using technology to improve urban services, efficiency, and quality of life", "Building tall buildings", "Creating more shopping malls", "Increasing population"],
        correctAnswer: "Using technology to improve urban services, efficiency, and quality of life",
        explanation: "Smart cities use IoT, AI, and data analytics to optimize urban services, reduce costs, and improve residents' quality of life",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Emerging Technologies - Smart Cities",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "Why is computational thinking important in problem-solving across all disciplines?",
        questionType: "multiple_choice",
        options: ["It provides a systematic approach to breaking down and solving complex problems", "It only works for math problems", "It requires expensive computers", "It's only useful for programmers"],
        correctAnswer: "It provides a systematic approach to breaking down and solving complex problems",
        explanation: "Computational thinking skills (decomposition, pattern recognition, abstraction, algorithms) are valuable for solving problems in any field",
        subject: "Computer Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Computational Thinking - Applications",
        difficulty: "hard",
        cognitiveLevel: "analysis"
      }
    ]
  }
};
