import type { SubjectQuestionBank } from "../../../shared/questionTypes";

export const english: SubjectQuestionBank = {
  subject: "English",
  grades: {
    "8-9": [
      {
        question: "Which word is a synonym for 'happy'?",
        questionType: "multiple_choice",
        options: ["Joyful", "Sad", "Angry", "Tired"],
        correctAnswer: "Joyful",
        explanation: "Joyful means full of joy or happiness, making it a synonym for happy",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Vocabulary - Synonyms",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "Identify the verb in this sentence: 'The students study hard for their exams.'",
        questionType: "multiple_choice",
        options: ["study", "students", "hard", "exams"],
        correctAnswer: "study",
        explanation: "'Study' is the action word (verb) in the sentence",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Grammar - Parts of Speech",
        difficulty: "easy",
        cognitiveLevel: "comprehension"
      },
      {
        question: "Which sentence is written in the passive voice?",
        questionType: "multiple_choice",
        options: ["The book was read by Ahmed.", "Ahmed read the book.", "Ahmed is reading the book.", "Ahmed will read the book."],
        correctAnswer: "The book was read by Ahmed.",
        explanation: "Passive voice focuses on the action (book was read) rather than the subject doing the action",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Grammar - Active and Passive Voice",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What is the main purpose of a thesis statement in an essay?",
        questionType: "multiple_choice",
        options: ["To state the main argument or point", "To conclude the essay", "To provide examples", "To introduce the topic"],
        correctAnswer: "To state the main argument or point",
        explanation: "A thesis statement presents the main argument that the essay will support",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Writing - Essay Structure",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "Which of these is a metaphor?",
        questionType: "multiple_choice",
        options: ["Time is money", "He runs like the wind", "The stars twinkled", "She sings beautifully"],
        correctAnswer: "Time is money",
        explanation: "A metaphor directly compares two unlike things without using 'like' or 'as'",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Literature - Figurative Language",
        difficulty: "medium",
        cognitiveLevel: "analysis"
      },
      {
        question: "What is the plural form of 'child'?",
        questionType: "multiple_choice",
        options: ["Children", "Childs", "Childes", "Childrens"],
        correctAnswer: "Children",
        explanation: "'Child' is an irregular noun with the plural form 'children'",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Grammar - Irregular Plurals",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "Which punctuation mark is used to show possession?",
        questionType: "multiple_choice",
        options: ["Apostrophe (')", "Comma (,)", "Period (.)", "Semicolon (;)"],
        correctAnswer: "Apostrophe (')",
        explanation: "The apostrophe is used to show possession, as in 'Sarah's book' or 'the dog's tail'",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Grammar - Punctuation",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What does the suffix '-ful' mean in words like 'beautiful' and 'helpful'?",
        questionType: "multiple_choice",
        options: ["Full of", "Without", "Before", "Against"],
        correctAnswer: "Full of",
        explanation: "The suffix '-ful' means 'full of' (beautiful = full of beauty, helpful = full of help)",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Vocabulary - Suffixes",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "Which sentence is grammatically correct?",
        questionType: "multiple_choice",
        options: ["She and I went to the market.", "Me and her went to the market.", "Her and me went to the market.", "I and she went to the market."],
        correctAnswer: "She and I went to the market.",
        explanation: "Subject pronouns (I, she) are used as subjects. 'She and I' is the correct form",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Grammar - Pronouns",
        difficulty: "easy",
        cognitiveLevel: "application"
      },
      {
        question: "What type of noun is 'happiness'?",
        questionType: "multiple_choice",
        options: ["Abstract noun", "Concrete noun", "Proper noun", "Collective noun"],
        correctAnswer: "Abstract noun",
        explanation: "Abstract nouns name ideas, feelings, or qualities that cannot be seen or touched (happiness, love, courage)",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Grammar - Types of Nouns",
        difficulty: "easy",
        cognitiveLevel: "comprehension"
      },
      {
        question: "In the sentence 'The dog barked loudly,' what is 'loudly'?",
        questionType: "multiple_choice",
        options: ["Adverb", "Adjective", "Noun", "Verb"],
        correctAnswer: "Adverb",
        explanation: "'Loudly' is an adverb that describes how the dog barked (modifies the verb 'barked')",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Grammar - Adverbs",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "Which literary device gives human qualities to non-human things?",
        questionType: "multiple_choice",
        options: ["Personification", "Simile", "Hyperbole", "Alliteration"],
        correctAnswer: "Personification",
        explanation: "Personification gives human characteristics to animals, objects, or ideas (e.g., 'The wind whispered')",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Literature - Literary Devices",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What is the correct past tense of 'run'?",
        questionType: "multiple_choice",
        options: ["Ran", "Runned", "Running", "Runs"],
        correctAnswer: "Ran",
        explanation: "'Run' is an irregular verb with the past tense form 'ran'",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Grammar - Irregular Verbs",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "Which word is an antonym for 'expand'?",
        questionType: "multiple_choice",
        options: ["Contract", "Grow", "Enlarge", "Increase"],
        correctAnswer: "Contract",
        explanation: "'Contract' means to become smaller, making it the opposite (antonym) of 'expand'",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Vocabulary - Antonyms",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "In a narrative, what is the 'climax'?",
        questionType: "multiple_choice",
        options: ["The point of highest tension or turning point", "The introduction of characters", "The ending of the story", "The background information"],
        correctAnswer: "The point of highest tension or turning point",
        explanation: "The climax is the most intense or important point in a story, where the main conflict reaches its peak",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Literature - Story Elements",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "Which sentence uses a simile?",
        questionType: "multiple_choice",
        options: ["Her smile was as bright as the sun.", "Her smile lit up the room.", "She smiled happily.", "The room was bright."],
        correctAnswer: "Her smile was as bright as the sun.",
        explanation: "A simile compares two things using 'like' or 'as'",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Literature - Figurative Language",
        difficulty: "easy",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What is the subject in the sentence: 'After school, the students played football'?",
        questionType: "multiple_choice",
        options: ["The students", "After school", "Played", "Football"],
        correctAnswer: "The students",
        explanation: "The subject is who or what the sentence is about. 'The students' is the subject performing the action",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Grammar - Sentence Structure",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "Which transition word shows contrast?",
        questionType: "multiple_choice",
        options: ["However", "Furthermore", "Therefore", "Similarly"],
        correctAnswer: "However",
        explanation: "'However' is a transition word that introduces a contrasting idea or opposite viewpoint",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Writing - Transitions",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What is the main difference between a fact and an opinion?",
        questionType: "multiple_choice",
        options: ["Facts can be proven true, opinions are beliefs", "Facts are always longer than opinions", "Opinions use more adjectives", "Facts come from books only"],
        correctAnswer: "Facts can be proven true, opinions are beliefs",
        explanation: "Facts are statements that can be verified as true or false, while opinions are personal beliefs or judgments",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Reading - Critical Thinking",
        difficulty: "hard",
        cognitiveLevel: "analysis"
      },
      {
        question: "Which sentence correctly uses a compound sentence structure?",
        questionType: "multiple_choice",
        options: ["I wanted to go to the park, but it was raining.", "Going to the park.", "The park was closed.", "I went to the park and the mall and the library."],
        correctAnswer: "I wanted to go to the park, but it was raining.",
        explanation: "A compound sentence joins two independent clauses with a coordinating conjunction (but, and, or, so)",
        subject: "English",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Grammar - Sentence Types",
        difficulty: "hard",
        cognitiveLevel: "application"
      }
    ],
    "10-12": [
      {
        question: "In which type of text would you most likely find persuasive language and rhetorical questions?",
        questionType: "multiple_choice",
        options: ["Argumentative essay", "Narrative story", "Dictionary entry", "Lab report"],
        correctAnswer: "Argumentative essay",
        explanation: "Argumentative essays use persuasive techniques like rhetorical questions to convince readers",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Writing - Text Types",
        difficulty: "easy",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What does the prefix 'anti-' mean in words like 'antibiotic' and 'antisocial'?",
        questionType: "multiple_choice",
        options: ["Against or opposite", "Before", "Together", "Around"],
        correctAnswer: "Against or opposite",
        explanation: "'Anti-' is a prefix meaning against or opposite (antibiotic = against bacteria)",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Vocabulary - Prefixes and Suffixes",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "Which sentence uses a semicolon correctly?",
        questionType: "multiple_choice",
        options: ["I love reading; it helps me relax.", "I love; reading books.", "Reading is fun; and educational.", "The book; was interesting."],
        correctAnswer: "I love reading; it helps me relax.",
        explanation: "Semicolons connect two related independent clauses without a conjunction",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Grammar - Punctuation",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "What literary device is used in: 'The classroom was a zoo'?",
        questionType: "multiple_choice",
        options: ["Metaphor", "Simile", "Personification", "Alliteration"],
        correctAnswer: "Metaphor",
        explanation: "A metaphor directly states one thing is another to make a comparison",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Literature - Literary Devices",
        difficulty: "easy",
        cognitiveLevel: "comprehension"
      },
      {
        question: "In critical reading, what does it mean to 'infer'?",
        questionType: "multiple_choice",
        options: ["To draw conclusions based on evidence and reasoning", "To memorize the text", "To summarize the main points", "To copy the author's words"],
        correctAnswer: "To draw conclusions based on evidence and reasoning",
        explanation: "Inference involves using clues in the text along with your own knowledge to draw conclusions",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Reading - Comprehension Skills",
        difficulty: "medium",
        cognitiveLevel: "analysis"
      },
      {
        question: "What is a 'theme' in literature?",
        questionType: "multiple_choice",
        options: ["The central message or insight about life", "The setting of the story", "The main character", "The plot summary"],
        correctAnswer: "The central message or insight about life",
        explanation: "A theme is the underlying universal idea or message that the author explores throughout the work",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Literature - Theme",
        difficulty: "easy",
        cognitiveLevel: "comprehension"
      },
      {
        question: "Which sentence demonstrates correct subject-verb agreement?",
        questionType: "multiple_choice",
        options: ["The team of players is ready.", "The team of players are ready.", "The team of players be ready.", "The team of players was being ready."],
        correctAnswer: "The team of players is ready.",
        explanation: "Collective nouns like 'team' take singular verbs when acting as a unit",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Grammar - Subject-Verb Agreement",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "What does 'chronological order' mean in writing?",
        questionType: "multiple_choice",
        options: ["Arranged in time sequence", "Arranged by importance", "Arranged alphabetically", "Arranged by topic"],
        correctAnswer: "Arranged in time sequence",
        explanation: "Chronological order means organizing events in the order they occurred in time",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Writing - Organization",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "Which word is correctly spelled?",
        questionType: "multiple_choice",
        options: ["Accommodate", "Acommodate", "Accomodate", "Acomodate"],
        correctAnswer: "Accommodate",
        explanation: "'Accommodate' has two c's and two m's - a commonly misspelled word",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Spelling - Common Errors",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is the purpose of a counterargument in an argumentative essay?",
        questionType: "multiple_choice",
        options: ["To acknowledge and refute opposing viewpoints", "To confuse the reader", "To change your position", "To end the essay"],
        correctAnswer: "To acknowledge and refute opposing viewpoints",
        explanation: "Counterarguments strengthen your essay by showing you've considered other perspectives and can defend your position",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Writing - Argumentation",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What is 'irony' in literature?",
        questionType: "multiple_choice",
        options: ["A contrast between expectation and reality", "A comparison using 'like' or 'as'", "Repetition of initial sounds", "Extreme exaggeration"],
        correctAnswer: "A contrast between expectation and reality",
        explanation: "Irony occurs when what happens is different from what is expected or what is said differs from what is meant",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Literature - Literary Devices",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "Which sentence uses parallel structure correctly?",
        questionType: "multiple_choice",
        options: ["She enjoys reading, writing, and hiking.", "She enjoys reading, to write, and hiking.", "She enjoys to read, writing, and to hike.", "She enjoys reading, writes, and to hike."],
        correctAnswer: "She enjoys reading, writing, and hiking.",
        explanation: "Parallel structure uses the same grammatical form for items in a series (all gerunds: reading, writing, hiking)",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Grammar - Parallel Structure",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "What is the difference between 'its' and 'it's'?",
        questionType: "multiple_choice",
        options: ["'Its' shows possession; 'it's' means 'it is'", "'Its' means 'it is'; 'it's' shows possession", "They are interchangeable", "Both show possession"],
        correctAnswer: "'Its' shows possession; 'it's' means 'it is'",
        explanation: "'Its' is possessive (the dog wagged its tail), while 'it's' is a contraction of 'it is' or 'it has'",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Grammar - Common Errors",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is 'tone' in writing?",
        questionType: "multiple_choice",
        options: ["The author's attitude toward the subject", "The main idea", "The genre of writing", "The length of sentences"],
        correctAnswer: "The author's attitude toward the subject",
        explanation: "Tone reflects the author's attitude or feelings through word choice and style (formal, informal, serious, humorous, etc.)",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Literature - Tone and Mood",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "Which citation style is commonly used for humanities subjects?",
        questionType: "multiple_choice",
        options: ["MLA", "APA", "Chicago", "IEEE"],
        correctAnswer: "MLA",
        explanation: "MLA (Modern Language Association) style is typically used for English, literature, and other humanities subjects",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Writing - Research and Citations",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is a 'complex sentence'?",
        questionType: "multiple_choice",
        options: ["A sentence with one independent clause and at least one dependent clause", "A very long sentence", "A sentence with two independent clauses", "A sentence with multiple adjectives"],
        correctAnswer: "A sentence with one independent clause and at least one dependent clause",
        explanation: "Complex sentences contain an independent clause and one or more dependent clauses joined by subordinating conjunctions",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Grammar - Sentence Types",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "In Shakespeare's plays, what is a 'soliloquy'?",
        questionType: "multiple_choice",
        options: ["A speech by a character alone on stage revealing inner thoughts", "A conversation between two characters", "The opening scene", "A song performed by the chorus"],
        correctAnswer: "A speech by a character alone on stage revealing inner thoughts",
        explanation: "A soliloquy is when a character speaks alone, revealing their thoughts and feelings to the audience",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Literature - Drama",
        difficulty: "medium",
        cognitiveLevel: "knowledge"
      },
      {
        question: "Which phrase contains a dangling modifier? ",
        questionType: "multiple_choice",
        options: ["Walking to school, the rain started pouring.", "While walking to school, I got wet from the rain.", "The rain poured as I walked to school.", "I was walking to school when it rained."],
        correctAnswer: "Walking to school, the rain started pouring.",
        explanation: "This is a dangling modifier because 'walking to school' illogically modifies 'rain' instead of a person",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Grammar - Modifiers",
        difficulty: "hard",
        cognitiveLevel: "analysis"
      },
      {
        question: "What is the primary purpose of a literature review in research writing?",
        questionType: "multiple_choice",
        options: ["To summarize and analyze existing research on a topic", "To give personal opinions", "To create fictional stories", "To list random facts"],
        correctAnswer: "To summarize and analyze existing research on a topic",
        explanation: "A literature review examines scholarly sources to establish what is already known about a topic",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Writing - Academic Writing",
        difficulty: "hard",
        cognitiveLevel: "comprehension"
      },
      {
        question: "Which of the following best demonstrates effective paraphrasing?",
        questionType: "multiple_choice",
        options: ["Rewording the original text in your own words while maintaining the meaning", "Copying the text word-for-word with quotation marks", "Changing only one or two words", "Removing all important details"],
        correctAnswer: "Rewording the original text in your own words while maintaining the meaning",
        explanation: "Paraphrasing involves expressing someone else's ideas in your own words while keeping the original meaning",
        subject: "English",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Writing - Research Skills",
        difficulty: "hard",
        cognitiveLevel: "application"
      }
    ]
  }
};
