import type { SubjectQuestionBank } from "../../../shared/questionTypes";

export const mathematics: SubjectQuestionBank = {
  subject: "Mathematics",
  grades: {
    "8-9": [
      {
        question: "Solve for x: 3x + 7 = 22",
        questionType: "multiple_choice",
        options: ["x = 3", "x = 5", "x = 7", "x = 9"],
        correctAnswer: "x = 5",
        explanation: "Subtract 7 from both sides: 3x = 15. Divide by 3: x = 5",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Algebra - Linear Equations",
        difficulty: "easy",
        cognitiveLevel: "application"
      },
      {
        question: "What is the area of a circle with radius 7 cm? (Use π ≈ 3.14)",
        questionType: "multiple_choice",
        options: ["153.86 cm²", "43.96 cm²", "21.98 cm²", "615.44 cm²"],
        correctAnswer: "153.86 cm²",
        explanation: "Area = πr² = 3.14 × 7² = 3.14 × 49 = 153.86 cm²",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Geometry - Circles",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "A shop offers a 25% discount on an item priced at AED 200. What is the final price?",
        questionType: "multiple_choice",
        options: ["AED 150", "AED 175", "AED 160", "AED 180"],
        correctAnswer: "AED 150",
        explanation: "Discount = 25% of 200 = 50. Final price = 200 - 50 = AED 150",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Financial Literacy - Percentages",
        difficulty: "easy",
        cognitiveLevel: "application"
      },
      {
        question: "In a survey of 50 students, 30 like football and 25 like basketball. If 10 like both, how many like only football?",
        questionType: "multiple_choice",
        options: ["20 students", "15 students", "25 students", "30 students"],
        correctAnswer: "20 students",
        explanation: "Only football = Total football - Both = 30 - 10 = 20 students",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Data - Set Theory",
        difficulty: "medium",
        cognitiveLevel: "analysis"
      },
      {
        question: "What is the probability of rolling a number greater than 4 on a standard six-sided die?",
        questionType: "multiple_choice",
        options: ["1/3", "1/2", "2/3", "1/6"],
        correctAnswer: "1/3",
        explanation: "Favorable outcomes: 5 and 6 (2 outcomes). Total outcomes: 6. Probability = 2/6 = 1/3",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Probability - Basic Probability",
        difficulty: "easy",
        cognitiveLevel: "comprehension"
      },
      {
        question: "Simplify: 2x² + 3x - 5 + 4x² - x + 2",
        questionType: "multiple_choice",
        options: ["6x² + 2x - 3", "6x² + 4x - 7", "2x² + 2x - 3", "6x² + 2x + 3"],
        correctAnswer: "6x² + 2x - 3",
        explanation: "Combine like terms: (2x² + 4x²) + (3x - x) + (-5 + 2) = 6x² + 2x - 3",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Algebra - Polynomials",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "The ratio of boys to girls in a class is 3:2. If there are 15 boys, how many girls are there?",
        questionType: "multiple_choice",
        options: ["10 girls", "12 girls", "8 girls", "6 girls"],
        correctAnswer: "10 girls",
        explanation: "3:2 means for every 3 boys there are 2 girls. 15÷3=5, so multiply 2×5=10 girls",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Numbers - Ratios and Proportions",
        difficulty: "easy",
        cognitiveLevel: "application"
      },
      {
        question: "What is the median of the data set: 5, 12, 8, 15, 3, 9?",
        questionType: "multiple_choice",
        options: ["8.5", "9", "8", "12"],
        correctAnswer: "8.5",
        explanation: "Arrange in order: 3, 5, 8, 9, 12, 15. Median is average of middle two: (8+9)/2 = 8.5",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Data - Measures of Central Tendency",
        difficulty: "medium",
        cognitiveLevel: "analysis"
      },
      {
        question: "Convert 0.75 to a fraction in simplest form",
        questionType: "multiple_choice",
        options: ["3/4", "7/10", "15/20", "75/100"],
        correctAnswer: "3/4",
        explanation: "0.75 = 75/100. Divide both by 25: 75÷25 = 3, 100÷25 = 4, so 3/4",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Numbers - Fractions and Decimals",
        difficulty: "easy",
        cognitiveLevel: "application"
      },
      {
        question: "If a rectangular garden is 12 m long and 8 m wide, what is its perimeter?",
        questionType: "multiple_choice",
        options: ["40 m", "96 m", "20 m", "48 m"],
        correctAnswer: "40 m",
        explanation: "Perimeter = 2(length + width) = 2(12 + 8) = 2(20) = 40 m",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Geometry - Perimeter and Area",
        difficulty: "easy",
        cognitiveLevel: "application"
      },
      {
        question: "Solve for y: 5y - 3 = 2y + 9",
        questionType: "multiple_choice",
        options: ["y = 4", "y = 6", "y = 3", "y = 2"],
        correctAnswer: "y = 4",
        explanation: "Subtract 2y from both sides: 3y - 3 = 9. Add 3: 3y = 12. Divide by 3: y = 4",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Algebra - Linear Equations",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "What is 15% of 200?",
        questionType: "multiple_choice",
        options: ["30", "15", "45", "3"],
        correctAnswer: "30",
        explanation: "15% of 200 = 0.15 × 200 = 30",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Numbers - Percentages",
        difficulty: "easy",
        cognitiveLevel: "application"
      },
      {
        question: "A triangle has angles measuring 45° and 65°. What is the measure of the third angle?",
        questionType: "multiple_choice",
        options: ["70°", "80°", "60°", "90°"],
        correctAnswer: "70°",
        explanation: "Sum of angles in triangle = 180°. Third angle = 180° - 45° - 65° = 70°",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Geometry - Triangles",
        difficulty: "easy",
        cognitiveLevel: "application"
      },
      {
        question: "Which number is a prime number?",
        questionType: "multiple_choice",
        options: ["17", "21", "27", "35"],
        correctAnswer: "17",
        explanation: "17 is divisible only by 1 and itself. 21=3×7, 27=3×9, 35=5×7 are composite",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Numbers - Prime and Composite",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "Simplify: √64",
        questionType: "multiple_choice",
        options: ["8", "32", "4", "16"],
        correctAnswer: "8",
        explanation: "√64 = 8 because 8 × 8 = 64",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Numbers - Square Roots",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is the volume of a cube with side length 5 cm?",
        questionType: "multiple_choice",
        options: ["125 cm³", "75 cm³", "25 cm³", "15 cm³"],
        correctAnswer: "125 cm³",
        explanation: "Volume = side³ = 5³ = 5 × 5 × 5 = 125 cm³",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Geometry - Volume",
        difficulty: "easy",
        cognitiveLevel: "application"
      },
      {
        question: "If 3x = 27, what is the value of x?",
        questionType: "multiple_choice",
        options: ["9", "24", "30", "81"],
        correctAnswer: "9",
        explanation: "Divide both sides by 3: x = 27 ÷ 3 = 9",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Algebra - Basic Equations",
        difficulty: "easy",
        cognitiveLevel: "application"
      },
      {
        question: "A bag contains 4 red marbles, 3 blue marbles, and 5 green marbles. What is the probability of randomly selecting a blue marble?",
        questionType: "multiple_choice",
        options: ["3/12 or 1/4", "3/7", "1/3", "1/2"],
        correctAnswer: "3/12 or 1/4",
        explanation: "Total marbles = 4 + 3 + 5 = 12. P(blue) = 3/12 = 1/4",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Probability - Basic Probability",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "Express 2³ × 2⁴ as a single power of 2",
        questionType: "multiple_choice",
        options: ["2⁷", "2¹²", "4⁷", "2"],
        correctAnswer: "2⁷",
        explanation: "When multiplying powers with same base, add exponents: 2³⁺⁴ = 2⁷",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Numbers - Exponents",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "The scale on a map is 1:50000. If two cities are 4 cm apart on the map, what is the actual distance between them?",
        questionType: "multiple_choice",
        options: ["2 km", "200 km", "20 km", "200 m"],
        correctAnswer: "2 km",
        explanation: "Actual distance = 4 × 50000 = 200000 cm = 2000 m = 2 km",
        subject: "Mathematics",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Numbers - Scale and Measurement",
        difficulty: "hard",
        cognitiveLevel: "analysis"
      }
    ],
    "10-12": [
      {
        question: "Solve the system of equations: 2x + y = 7 and x - y = 2",
        questionType: "multiple_choice",
        options: ["x = 3, y = 1", "x = 2, y = 3", "x = 4, y = -1", "x = 1, y = 5"],
        correctAnswer: "x = 3, y = 1",
        explanation: "Add equations: 3x = 9, so x = 3. Substitute: 3 - y = 2, so y = 1",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Algebra - Systems of Equations",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "What is the value of sin(30°)?",
        questionType: "multiple_choice",
        options: ["1/2", "√3/2", "1", "√2/2"],
        correctAnswer: "1/2",
        explanation: "sin(30°) = 1/2 is a standard trigonometric value for special angles",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Trigonometry - Special Angles",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "Find the 10th term of the arithmetic sequence: 3, 7, 11, 15, ...",
        questionType: "multiple_choice",
        options: ["39", "43", "47", "35"],
        correctAnswer: "39",
        explanation: "First term a = 3, common difference d = 4. Formula: an = a + (n-1)d = 3 + 9(4) = 39",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Sequences and Series - Arithmetic Sequences",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "If f(x) = 2x² - 3x + 1, what is f(3)?",
        questionType: "multiple_choice",
        options: ["10", "12", "8", "15"],
        correctAnswer: "10",
        explanation: "f(3) = 2(3)² - 3(3) + 1 = 2(9) - 9 + 1 = 18 - 9 + 1 = 10",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Functions - Polynomial Functions",
        difficulty: "easy",
        cognitiveLevel: "application"
      },
      {
        question: "What is the equation of a line with slope 2 passing through point (1, 3)?",
        questionType: "multiple_choice",
        options: ["y = 2x + 1", "y = 2x + 3", "y = 2x - 1", "y = 2x + 5"],
        correctAnswer: "y = 2x + 1",
        explanation: "Using point-slope form: y - 3 = 2(x - 1), simplify: y = 2x + 1",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Coordinate Geometry - Linear Functions",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "A box contains 5 red balls and 3 blue balls. If two balls are drawn without replacement, what is the probability both are red?",
        questionType: "multiple_choice",
        options: ["5/14", "10/28", "5/8", "25/64"],
        correctAnswer: "5/14",
        explanation: "P(both red) = (5/8) × (4/7) = 20/56 = 5/14",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Probability - Dependent Events",
        difficulty: "hard",
        cognitiveLevel: "analysis"
      },
      {
        question: "Factor completely: x² - 9",
        questionType: "multiple_choice",
        options: ["(x - 3)(x + 3)", "(x - 9)(x + 1)", "(x - 3)²", "Cannot be factored"],
        correctAnswer: "(x - 3)(x + 3)",
        explanation: "This is difference of squares: a² - b² = (a - b)(a + b), so x² - 9 = (x - 3)(x + 3)",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Algebra - Factoring Polynomials",
        difficulty: "easy",
        cognitiveLevel: "comprehension"
      },
      {
        question: "The mean of five numbers is 12. If four of the numbers are 8, 10, 14, and 15, what is the fifth number?",
        questionType: "multiple_choice",
        options: ["13", "11", "12", "14"],
        correctAnswer: "13",
        explanation: "Sum = 12 × 5 = 60. Known sum = 8 + 10 + 14 + 15 = 47. Fifth number = 60 - 47 = 13",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Statistics - Mean and Average",
        difficulty: "medium",
        cognitiveLevel: "analysis"
      },
      {
        question: "Solve the quadratic equation: x² - 5x + 6 = 0",
        questionType: "multiple_choice",
        options: ["x = 2 or x = 3", "x = 1 or x = 6", "x = -2 or x = -3", "x = 5 or x = 6"],
        correctAnswer: "x = 2 or x = 3",
        explanation: "Factor: (x - 2)(x - 3) = 0, so x = 2 or x = 3. Check: 2² - 5(2) + 6 = 0 ✓",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Algebra - Quadratic Equations",
        difficulty: "easy",
        cognitiveLevel: "application"
      },
      {
        question: "What is the value of cos(60°)?",
        questionType: "multiple_choice",
        options: ["1/2", "√3/2", "1", "0"],
        correctAnswer: "1/2",
        explanation: "cos(60°) = 1/2 is a standard trigonometric value for special angles",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Trigonometry - Special Angles",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "Find the sum of the first 10 terms of the geometric sequence: 2, 6, 18, 54, ...",
        questionType: "multiple_choice",
        options: ["59048", "29524", "19682", "39366"],
        correctAnswer: "59048",
        explanation: "a = 2, r = 3. Formula: Sn = a(rⁿ - 1)/(r - 1) = 2(3¹⁰ - 1)/(3 - 1) = 2(59049 - 1)/2 = 59048",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Sequences and Series - Geometric Sequences",
        difficulty: "hard",
        cognitiveLevel: "application"
      },
      {
        question: "What is the derivative of f(x) = 3x² + 2x - 5?",
        questionType: "multiple_choice",
        options: ["6x + 2", "3x² + 2", "6x - 5", "3x + 2"],
        correctAnswer: "6x + 2",
        explanation: "Using power rule: d/dx(3x²) = 6x, d/dx(2x) = 2, d/dx(-5) = 0. So f'(x) = 6x + 2",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Calculus - Derivatives",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "Convert log₂(32) to its numerical value",
        questionType: "multiple_choice",
        options: ["5", "4", "6", "3"],
        correctAnswer: "5",
        explanation: "log₂(32) asks: 2 to what power equals 32? Since 2⁵ = 32, log₂(32) = 5",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Algebra - Logarithms",
        difficulty: "easy",
        cognitiveLevel: "application"
      },
      {
        question: "What is the distance between points A(1, 2) and B(4, 6) in the coordinate plane?",
        questionType: "multiple_choice",
        options: ["5", "7", "√7", "√13"],
        correctAnswer: "5",
        explanation: "Distance = √[(4-1)² + (6-2)²] = √[9 + 16] = √25 = 5",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Coordinate Geometry - Distance Formula",
        difficulty: "easy",
        cognitiveLevel: "application"
      },
      {
        question: "In a normal distribution, approximately what percentage of data falls within one standard deviation of the mean?",
        questionType: "multiple_choice",
        options: ["68%", "95%", "99.7%", "50%"],
        correctAnswer: "68%",
        explanation: "The empirical rule states that approximately 68% of data falls within one standard deviation of the mean",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Statistics - Normal Distribution",
        difficulty: "medium",
        cognitiveLevel: "knowledge"
      },
      {
        question: "If matrix A = [2 3; 1 4], what is the determinant of A?",
        questionType: "multiple_choice",
        options: ["5", "8", "11", "3"],
        correctAnswer: "5",
        explanation: "For a 2×2 matrix [a b; c d], det = ad - bc = (2)(4) - (3)(1) = 8 - 3 = 5",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Linear Algebra - Matrices",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "Simplify: (x³)⁴",
        questionType: "multiple_choice",
        options: ["x¹²", "x⁷", "x⁶⁴", "4x³"],
        correctAnswer: "x¹²",
        explanation: "When raising a power to a power, multiply the exponents: (x³)⁴ = x³ˣ⁴ = x¹²",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Algebra - Exponent Laws",
        difficulty: "easy",
        cognitiveLevel: "application"
      },
      {
        question: "The surface area of a sphere with radius r is given by 4πr². What is the surface area when r = 3 cm? (Use π ≈ 3.14)",
        questionType: "multiple_choice",
        options: ["113.04 cm²", "28.26 cm²", "36 cm²", "37.68 cm²"],
        correctAnswer: "113.04 cm²",
        explanation: "Surface area = 4πr² = 4 × 3.14 × 3² = 4 × 3.14 × 9 = 113.04 cm²",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Geometry - 3D Shapes",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "If tan(θ) = 3/4 and θ is in the first quadrant, what is sin(θ)?",
        questionType: "multiple_choice",
        options: ["3/5", "4/5", "3/4", "4/3"],
        correctAnswer: "3/5",
        explanation: "tan = opposite/adjacent = 3/4. Using Pythagorean theorem: hypotenuse = √(3² + 4²) = 5. Therefore sin(θ) = opposite/hypotenuse = 3/5",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Trigonometry - Trigonometric Ratios",
        difficulty: "hard",
        cognitiveLevel: "analysis"
      },
      {
        question: "Which of the following represents an inverse variation?",
        questionType: "multiple_choice",
        options: ["xy = 12", "y = 3x + 5", "y = x²", "y = 2x"],
        correctAnswer: "xy = 12",
        explanation: "Inverse variation has the form xy = k (constant). When x increases, y decreases proportionally",
        subject: "Mathematics",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Algebra - Variation",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      }
    ]
  }
};
