import type { SubjectQuestionBank } from "../../../shared/questionTypes";

export const science: SubjectQuestionBank = {
  subject: "Science",
  grades: {
    "8-9": [
      {
        question: "What is the process by which plants make their own food using sunlight?",
        questionType: "multiple_choice",
        options: ["Photosynthesis", "Respiration", "Digestion", "Fermentation"],
        correctAnswer: "Photosynthesis",
        explanation: "Photosynthesis is the process where plants convert sunlight, water, and carbon dioxide into glucose and oxygen",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Biology - Photosynthesis",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "Which state of matter has a definite volume but no definite shape?",
        questionType: "multiple_choice",
        options: ["Liquid", "Solid", "Gas", "Plasma"],
        correctAnswer: "Liquid",
        explanation: "Liquids have a definite volume but take the shape of their container",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Chemistry - States of Matter",
        difficulty: "easy",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What type of energy is stored in food?",
        questionType: "multiple_choice",
        options: ["Chemical energy", "Kinetic energy", "Light energy", "Sound energy"],
        correctAnswer: "Chemical energy",
        explanation: "Food stores chemical energy in the bonds between atoms that is released during digestion",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Physics - Energy Forms",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is the chemical formula for water?",
        questionType: "multiple_choice",
        options: ["H₂O", "CO₂", "O₂", "H₂O₂"],
        correctAnswer: "H₂O",
        explanation: "Water consists of two hydrogen atoms and one oxygen atom: H₂O",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Chemistry - Chemical Formulas",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "Which organ in the human body pumps blood?",
        questionType: "multiple_choice",
        options: ["Heart", "Lungs", "Liver", "Kidneys"],
        correctAnswer: "Heart",
        explanation: "The heart is the organ responsible for pumping blood throughout the body",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Biology - Human Body Systems",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What happens to the volume of a gas when temperature increases (at constant pressure)?",
        questionType: "multiple_choice",
        options: ["Volume increases", "Volume decreases", "Volume stays the same", "Gas becomes liquid"],
        correctAnswer: "Volume increases",
        explanation: "According to Charles's Law, at constant pressure, the volume of a gas increases as temperature increases",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Physics - Gas Laws",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "Which part of the cell controls all cellular activities and contains DNA?",
        questionType: "multiple_choice",
        options: ["Nucleus", "Cytoplasm", "Cell membrane", "Mitochondria"],
        correctAnswer: "Nucleus",
        explanation: "The nucleus is the control center of the cell, containing genetic material (DNA) that directs all cellular functions",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Biology - Cell Structure",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is the pH value of a neutral solution?",
        questionType: "multiple_choice",
        options: ["7", "0", "14", "1"],
        correctAnswer: "7",
        explanation: "The pH scale ranges from 0-14. A pH of 7 is neutral; below 7 is acidic, above 7 is basic",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Chemistry - Acids and Bases",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What type of rock is formed when magma cools and solidifies?",
        questionType: "multiple_choice",
        options: ["Igneous rock", "Sedimentary rock", "Metamorphic rock", "Limestone"],
        correctAnswer: "Igneous rock",
        explanation: "Igneous rocks form from the cooling and solidification of magma or lava",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Earth Science - Rock Cycle",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is the SI unit for measuring force?",
        questionType: "multiple_choice",
        options: ["Newton (N)", "Joule (J)", "Watt (W)", "Pascal (Pa)"],
        correctAnswer: "Newton (N)",
        explanation: "The Newton (N) is the SI unit for force, named after Sir Isaac Newton",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Physics - Forces and Motion",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "In a food chain, what are organisms that make their own food called?",
        questionType: "multiple_choice",
        options: ["Producers", "Consumers", "Decomposers", "Predators"],
        correctAnswer: "Producers",
        explanation: "Producers (like plants) make their own food through photosynthesis and form the base of food chains",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Biology - Ecosystems",
        difficulty: "easy",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What happens during a chemical reaction?",
        questionType: "multiple_choice",
        options: ["New substances are formed", "Only physical changes occur", "Atoms are created", "Mass is lost"],
        correctAnswer: "New substances are formed",
        explanation: "Chemical reactions involve breaking and forming chemical bonds, creating new substances with different properties",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Chemistry - Chemical Reactions",
        difficulty: "easy",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What is the relationship between speed, distance, and time?",
        questionType: "multiple_choice",
        options: ["Speed = Distance ÷ Time", "Speed = Distance × Time", "Speed = Time ÷ Distance", "Speed = Distance + Time"],
        correctAnswer: "Speed = Distance ÷ Time",
        explanation: "Speed is calculated by dividing the distance traveled by the time taken",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Physics - Motion",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "Which blood vessels carry blood away from the heart?",
        questionType: "multiple_choice",
        options: ["Arteries", "Veins", "Capillaries", "Lymph vessels"],
        correctAnswer: "Arteries",
        explanation: "Arteries carry oxygenated blood away from the heart to body tissues, while veins return blood to the heart",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Biology - Circulatory System",
        difficulty: "medium",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is the atomic number of an element?",
        questionType: "multiple_choice",
        options: ["The number of protons in the nucleus", "The number of neutrons", "The number of electrons", "The total mass"],
        correctAnswer: "The number of protons in the nucleus",
        explanation: "Atomic number equals the number of protons in an atom's nucleus, which defines the element",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Chemistry - Atomic Structure",
        difficulty: "medium",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What type of energy transformation occurs in a light bulb?",
        questionType: "multiple_choice",
        options: ["Electrical energy to light and heat", "Light energy to electrical", "Chemical to mechanical", "Nuclear to thermal"],
        correctAnswer: "Electrical energy to light and heat",
        explanation: "A light bulb converts electrical energy into light energy and heat energy",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Physics - Energy Transformations",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "Which process do plants use to release energy from glucose?",
        questionType: "multiple_choice",
        options: ["Respiration", "Photosynthesis", "Transpiration", "Germination"],
        correctAnswer: "Respiration",
        explanation: "Both plants and animals use cellular respiration to break down glucose and release energy",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Biology - Cellular Processes",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "According to the law of conservation of mass, what happens to mass during a chemical reaction?",
        questionType: "multiple_choice",
        options: ["Mass remains constant", "Mass increases", "Mass decreases", "Mass converts to energy"],
        correctAnswer: "Mass remains constant",
        explanation: "The law of conservation of mass states that mass is neither created nor destroyed in chemical reactions",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Chemistry - Conservation Laws",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "A ball is dropped from a height. As it falls, what happens to its potential and kinetic energy?",
        questionType: "multiple_choice",
        options: ["Potential energy decreases, kinetic energy increases", "Both increase", "Both decrease", "Potential increases, kinetic decreases"],
        correctAnswer: "Potential energy decreases, kinetic energy increases",
        explanation: "As the ball falls, gravitational potential energy converts to kinetic energy. Total mechanical energy remains constant",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Physics - Energy Conservation",
        difficulty: "hard",
        cognitiveLevel: "analysis"
      },
      {
        question: "If an organism has 46 chromosomes in its body cells, how many chromosomes will its gametes (sex cells) have?",
        questionType: "multiple_choice",
        options: ["23", "46", "92", "12"],
        correctAnswer: "23",
        explanation: "Gametes are produced through meiosis, which halves the chromosome number. Human gametes have 23 chromosomes",
        subject: "Science",
        gradeBand: "8-9",
        countryId: "uae",
        topic: "Biology - Cell Division",
        difficulty: "hard",
        cognitiveLevel: "application"
      }
    ],
    "10-12": [
      {
        question: "What is the acceleration of an object with mass 5 kg when a force of 20 N is applied? (Use F = ma)",
        questionType: "multiple_choice",
        options: ["4 m/s²", "100 m/s²", "25 m/s²", "0.25 m/s²"],
        correctAnswer: "4 m/s²",
        explanation: "Using Newton's second law F = ma: a = F/m = 20/5 = 4 m/s²",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Physics - Newton's Laws of Motion",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "In a redox reaction, what happens to the oxidizing agent?",
        questionType: "multiple_choice",
        options: ["It is reduced", "It is oxidized", "It remains unchanged", "It decomposes"],
        correctAnswer: "It is reduced",
        explanation: "The oxidizing agent accepts electrons and is itself reduced in the process",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Chemistry - Redox Reactions",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "Which organelle is known as the 'powerhouse of the cell'?",
        questionType: "multiple_choice",
        options: ["Mitochondria", "Nucleus", "Ribosome", "Golgi apparatus"],
        correctAnswer: "Mitochondria",
        explanation: "Mitochondria produce ATP through cellular respiration, providing energy for the cell",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Biology - Cell Biology",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is the SI unit for electric current?",
        questionType: "multiple_choice",
        options: ["Ampere (A)", "Volt (V)", "Ohm (Ω)", "Watt (W)"],
        correctAnswer: "Ampere (A)",
        explanation: "The ampere (A) is the SI base unit for measuring electric current",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Physics - Electricity",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "According to Mendel's law of segregation, what happens to alleles during gamete formation?",
        questionType: "multiple_choice",
        options: ["They separate so each gamete receives one allele", "They combine together", "They mutate", "They duplicate"],
        correctAnswer: "They separate so each gamete receives one allele",
        explanation: "Mendel's law of segregation states that allele pairs separate during gamete formation, with each gamete receiving one allele",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Biology - Genetics",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What is the voltage across a resistor with resistance 10 Ω carrying a current of 2 A? (Use Ohm's Law: V = IR)",
        questionType: "multiple_choice",
        options: ["20 V", "5 V", "12 V", "0.2 V"],
        correctAnswer: "20 V",
        explanation: "Using Ohm's Law: V = IR = 2 × 10 = 20 V",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Physics - Ohm's Law",
        difficulty: "easy",
        cognitiveLevel: "application"
      },
      {
        question: "What is the process by which cells divide to produce gametes (sex cells)?",
        questionType: "multiple_choice",
        options: ["Meiosis", "Mitosis", "Binary fission", "Budding"],
        correctAnswer: "Meiosis",
        explanation: "Meiosis is the specialized cell division that produces gametes with half the chromosome number",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Biology - Cell Division",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is the chemical symbol for gold?",
        questionType: "multiple_choice",
        options: ["Au", "Ag", "Fe", "Cu"],
        correctAnswer: "Au",
        explanation: "Gold's chemical symbol Au comes from its Latin name 'Aurum'",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Chemistry - Periodic Table",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is kinetic energy?",
        questionType: "multiple_choice",
        options: ["Energy of motion", "Stored energy", "Heat energy", "Light energy"],
        correctAnswer: "Energy of motion",
        explanation: "Kinetic energy is the energy an object possesses due to its motion, calculated as KE = ½mv²",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Physics - Energy",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "In a heterozygous individual (Aa), which allele is expressed in the phenotype?",
        questionType: "multiple_choice",
        options: ["The dominant allele", "The recessive allele", "Both equally", "Neither"],
        correctAnswer: "The dominant allele",
        explanation: "In heterozygous individuals, the dominant allele is expressed while the recessive allele is masked",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Biology - Genetics",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "What type of bond is formed when atoms share electrons?",
        questionType: "multiple_choice",
        options: ["Covalent bond", "Ionic bond", "Metallic bond", "Hydrogen bond"],
        correctAnswer: "Covalent bond",
        explanation: "Covalent bonds form when atoms share one or more pairs of electrons",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Chemistry - Chemical Bonding",
        difficulty: "medium",
        cognitiveLevel: "comprehension"
      },
      {
        question: "A car accelerates from rest to 20 m/s in 5 seconds. What is its acceleration?",
        questionType: "multiple_choice",
        options: ["4 m/s²", "100 m/s²", "25 m/s²", "15 m/s²"],
        correctAnswer: "4 m/s²",
        explanation: "Acceleration = (final velocity - initial velocity) / time = (20 - 0) / 5 = 4 m/s²",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Physics - Kinematics",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "What is the balanced equation for the combustion of methane (CH₄)?",
        questionType: "multiple_choice",
        options: ["CH₄ + 2O₂ → CO₂ + 2H₂O", "CH₄ + O₂ → CO₂ + H₂O", "CH₄ + 3O₂ → CO₂ + 2H₂O", "2CH₄ + O₂ → 2CO₂ + H₂O"],
        correctAnswer: "CH₄ + 2O₂ → CO₂ + 2H₂O",
        explanation: "Methane combustion: CH₄ + 2O₂ → CO₂ + 2H₂O. Atoms are balanced: 1C, 4H, 4O on each side",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Chemistry - Chemical Equations",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "Which biome receives less than 25 cm of rain per year?",
        questionType: "multiple_choice",
        options: ["Desert", "Tropical rainforest", "Temperate forest", "Grassland"],
        correctAnswer: "Desert",
        explanation: "Deserts are characterized by very low precipitation, typically less than 25 cm annually",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Biology - Ecosystems",
        difficulty: "easy",
        cognitiveLevel: "knowledge"
      },
      {
        question: "What is the work done when a force of 15 N moves an object 4 meters in the direction of the force?",
        questionType: "multiple_choice",
        options: ["60 J", "19 J", "11 J", "3.75 J"],
        correctAnswer: "60 J",
        explanation: "Work = Force × Distance = 15 N × 4 m = 60 Joules",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Physics - Work and Energy",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "What is the molarity of a solution containing 2 moles of NaCl dissolved in 4 liters of water?",
        questionType: "multiple_choice",
        options: ["0.5 M", "2 M", "8 M", "0.25 M"],
        correctAnswer: "0.5 M",
        explanation: "Molarity = moles of solute / liters of solution = 2 moles / 4 L = 0.5 M",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Chemistry - Solutions",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "In photosynthesis, what molecule is split to release oxygen?",
        questionType: "multiple_choice",
        options: ["Water (H₂O)", "Carbon dioxide (CO₂)", "Glucose (C₆H₁₂O₆)", "ATP"],
        correctAnswer: "Water (H₂O)",
        explanation: "During the light reactions of photosynthesis, water molecules are split (photolysis), releasing oxygen gas",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Biology - Photosynthesis",
        difficulty: "hard",
        cognitiveLevel: "comprehension"
      },
      {
        question: "Calculate the momentum of a 1500 kg car traveling at 20 m/s (momentum = mass × velocity)",
        questionType: "multiple_choice",
        options: ["30000 kg⋅m/s", "1520 kg⋅m/s", "75 kg⋅m/s", "1480 kg⋅m/s"],
        correctAnswer: "30000 kg⋅m/s",
        explanation: "Momentum = mass × velocity = 1500 kg × 20 m/s = 30000 kg⋅m/s",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Physics - Momentum",
        difficulty: "medium",
        cognitiveLevel: "application"
      },
      {
        question: "What happens to the equilibrium of the reaction N₂ + 3H₂ ⇌ 2NH₃ if pressure is increased?",
        questionType: "multiple_choice",
        options: ["Shifts right (toward NH₃ production)", "Shifts left (toward reactants)", "No change", "Reaction stops"],
        correctAnswer: "Shifts right (toward NH₃ production)",
        explanation: "According to Le Chatelier's principle, increasing pressure shifts equilibrium toward the side with fewer gas molecules (4 moles → 2 moles)",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Chemistry - Chemical Equilibrium",
        difficulty: "hard",
        cognitiveLevel: "analysis"
      },
      {
        question: "A wave has a frequency of 500 Hz and travels at 1500 m/s. What is its wavelength?",
        questionType: "multiple_choice",
        options: ["3 m", "0.33 m", "750000 m", "1000 m"],
        correctAnswer: "3 m",
        explanation: "Wavelength = velocity / frequency = 1500 m/s / 500 Hz = 3 m",
        subject: "Science",
        gradeBand: "10-12",
        countryId: "uae",
        topic: "Physics - Waves",
        difficulty: "hard",
        cognitiveLevel: "application"
      }
    ]
  }
};
