uploads = []

[[generated]]
id = "iBsm8KCOh16WimstOlovX"
uri = "file://client/public/og-image.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "KZUgeQbS9vBx2Iws2bcdU"
uri = "file://docs/future-path-white-paper-2026.docx"
type = "word_document"
title = "Future Path White Paper 2026 (.docx)"

[[outputs]]
id = "LgJV9VrsJX8UwVNJZxv74"
uri = "file://docs/future-pathways-white-paper-2026.docx"
type = "word_document"
title = "Future Pathways White Paper 2026 (Updated)"
