/**
 * Children's Values Questionnaire (CVQ) Seed Data
 * Based on Schwartz's Portrait Values Questionnaire (PVQ-40)
 * Adapted for ages 13-18 school students
 * 
 * 21 questions total: 3 per domain across 7 value domains
 * Response scale: 1-5 Likert (Not like me → Very much like me)
 */

import { db } from './db';
import { cvqItems, type InsertCvqItem } from '../shared/schema';

// CVQ Items based on validated PVQ-40 items, adapted for youth
// id and createdAt are auto-generated by database
export const CVQ_SEED_DATA: InsertCvqItem[] = [
  // ACHIEVEMENT - Personal success through demonstrating competence (3 items)
  {
    domain: 'achievement',
    position: 1,
    text: "It's very important to me to show my abilities. I want people to admire what I do.",
    version: '1.0.0',
  },
  {
    domain: 'achievement',
    position: 2,
    text: "Being very successful is important to me. I like to impress other people.",
    version: '1.0.0',
  },
  {
    domain: 'achievement',
    position: 3,
    text: "It is important to me to be ambitious. I want to show how capable I am.",
    version: '1.0.0',
  },

  // BENEVOLENCE - Preserving and enhancing the welfare of people close to you (3 items)
  {
    domain: 'benevolence',
    position: 1,
    text: "It's very important to me to help the people around me. I want to care for their well-being.",
    version: '1.0.0',
  },
  {
    domain: 'benevolence',
    position: 2,
    text: "It is important to me to be loyal to my friends. I want to devote myself to people close to me.",
    version: '1.0.0',
  },
  {
    domain: 'benevolence',
    position: 3,
    text: "It is important to me to respond to the needs of others. I try to support those I know.",
    version: '1.0.0',
  },

  // UNIVERSALISM - Understanding, appreciation, tolerance, and protection for all people and nature (3 items)
  {
    domain: 'universalism',
    position: 1,
    text: "I think it's important that every person in the world be treated equally. Everyone should have equal opportunities in life.",
    version: '1.0.0',
  },
  {
    domain: 'universalism',
    position: 2,
    text: "I strongly believe that people should care for nature. Looking after the environment is important to me.",
    version: '1.0.0',
  },
  {
    domain: 'universalism',
    position: 3,
    text: "I believe all the world's people should live in harmony. Promoting peace among all groups in the world is important to me.",
    version: '1.0.0',
  },

  // SELF-DIRECTION - Independent thought and action (3 items)
  {
    domain: 'self_direction',
    position: 1,
    text: "Thinking up new ideas and being creative is important to me. I like to do things in my own original way.",
    version: '1.0.0',
  },
  {
    domain: 'self_direction',
    position: 2,
    text: "It is important to me to make my own decisions about what I do. I like to be free to plan and choose my activities for myself.",
    version: '1.0.0',
  },
  {
    domain: 'self_direction',
    position: 3,
    text: "I think it's important to be interested in things. I like to be curious and try to understand all sorts of things.",
    version: '1.0.0',
  },

  // SECURITY - Safety, harmony, and stability of society, relationships, and self (3 items)
  {
    domain: 'security',
    position: 1,
    text: "It is important to me to live in secure surroundings. I avoid anything that might endanger my safety.",
    version: '1.0.0',
  },
  {
    domain: 'security',
    position: 2,
    text: "It is very important to me that my country be safe. I think the state must be on watch against threats from within and without.",
    version: '1.0.0',
  },
  {
    domain: 'security',
    position: 3,
    text: "I try hard to avoid getting sick. Staying healthy is very important to me.",
    version: '1.0.0',
  },

  // POWER - Social status, prestige, control over people and resources (3 items)
  {
    domain: 'power',
    position: 1,
    text: "It is important to me to be rich. I want to have a lot of money and expensive things.",
    version: '1.0.0',
  },
  {
    domain: 'power',
    position: 2,
    text: "It is important to me to get respect from others. I want people to do what I say.",
    version: '1.0.0',
  },
  {
    domain: 'power',
    position: 3,
    text: "I always want to be the one who makes the decisions. I like to be the leader.",
    version: '1.0.0',
  },

  // HEDONISM - Pleasure and sensuous gratification for oneself (3 items)
  {
    domain: 'hedonism',
    position: 1,
    text: "I seek every chance I can to have fun. It is important to me to do things that give me pleasure.",
    version: '1.0.0',
  },
  {
    domain: 'hedonism',
    position: 2,
    text: "Enjoying life's pleasures is important to me. I like to spoil myself.",
    version: '1.0.0',
  },
  {
    domain: 'hedonism',
    position: 3,
    text: "I really want to enjoy life. Having a good time is very important to me.",
    version: '1.0.0',
  },
];

/**
 * Seed CVQ items into database
 * Should be called during initial database seeding
 */
export async function seedCVQItems() {
  console.log('📋 Seeding CVQ items...');
  
  try {
    // Check if CVQ items already exist
    const existingItems = await db.select().from(cvqItems);
    
    if (existingItems.length > 0) {
      console.log(`  CVQ items already exist (${existingItems.length} items), skipping...`);
      return;
    }

    // Insert all 21 CVQ items (id and createdAt auto-generated)
    await db.insert(cvqItems).values(CVQ_SEED_DATA as any);
    
    console.log(`✓ Created ${CVQ_SEED_DATA.length} CVQ items (7 domains × 3 questions)`);
    console.log('  Domains: Achievement, Benevolence, Universalism, Self-Direction, Security, Power, Hedonism');
  } catch (error) {
    console.error('Error seeding CVQ items:', error);
    throw error;
  }
}
