import { InsertWefSkill, InsertCareerWefSkillAffinity } from "../shared/schema";

// WEF (World Economic Forum) 16 Skills Framework - 2025
// Source: New Vision for Education, WEF Future of Jobs Report 2025

export const WEF_16_SKILLS: Omit<InsertWefSkill, "id" | "createdAt">[] = [
  // === FOUNDATIONAL LITERACIES (6 skills) ===
  {
    name: "Literacy",
    competencyType: "foundational_literacy",
    category: "Communication",
    description: "Ability to read, write, and communicate effectively in multiple contexts",
    displayOrder: 1,
    assessmentApplicable: false, // Derived from quiz scores
    relatedSubjects: ["English", "Arabic"],
    version: "2025",
  },
  {
    name: "Numeracy",
    competencyType: "foundational_literacy",
    category: "Mathematical Thinking",
    description: "Ability to reason with numbers and mathematical concepts to solve problems",
    displayOrder: 2,
    assessmentApplicable: false, // Derived from quiz scores
    relatedSubjects: ["Mathematics"],
    version: "2025",
  },
  {
    name: "Scientific Literacy",
    competencyType: "foundational_literacy",
    category: "Scientific Thinking",
    description: "Understanding scientific concepts, methods, and ability to apply scientific reasoning",
    displayOrder: 3,
    assessmentApplicable: false, // Derived from quiz scores
    relatedSubjects: ["Science"],
    version: "2025",
  },
  {
    name: "ICT Literacy",
    competencyType: "foundational_literacy",
    category: "Digital Skills",
    description: "Proficiency in using digital technologies, communication tools, and networks",
    displayOrder: 4,
    assessmentApplicable: false, // Derived from quiz scores
    relatedSubjects: ["Computer Science"],
    version: "2025",
  },
  {
    name: "Financial Literacy",
    competencyType: "foundational_literacy",
    category: "Economic Thinking",
    description: "Understanding financial concepts, managing personal finances, and economic decision-making",
    displayOrder: 5,
    assessmentApplicable: false, // Derived from quiz scores
    relatedSubjects: ["Mathematics", "Social Studies"],
    version: "2025",
  },
  {
    name: "Cultural and Civic Literacy",
    competencyType: "foundational_literacy",
    category: "Social Awareness",
    description: "Understanding cultural diversity, civic responsibilities, and global citizenship",
    displayOrder: 6,
    assessmentApplicable: false, // Derived from quiz scores
    relatedSubjects: ["Social Studies", "Arabic"],
    version: "2025",
  },
  
  // === COMPETENCIES AND CHARACTER QUALITIES (10 skills) ===
  {
    name: "Critical Thinking and Problem Solving",
    competencyType: "competency",
    category: "Cognitive Skills",
    description: "Ability to analyze information, evaluate evidence, and solve complex problems systematically",
    displayOrder: 7,
    assessmentApplicable: true, // Will have SEL assessment questions
    relatedSubjects: null,
    version: "2025",
  },
  {
    name: "Creativity",
    competencyType: "competency",
    category: "Cognitive Skills",
    description: "Ability to generate novel ideas, think outside the box, and approach challenges innovatively",
    displayOrder: 8,
    assessmentApplicable: true,
    relatedSubjects: null,
    version: "2025",
  },
  {
    name: "Communication",
    competencyType: "competency",
    category: "Social Skills",
    description: "Ability to express ideas clearly, listen actively, and adapt communication to different audiences",
    displayOrder: 9,
    assessmentApplicable: true,
    relatedSubjects: null,
    version: "2025",
  },
  {
    name: "Collaboration",
    competencyType: "competency",
    category: "Social Skills",
    description: "Ability to work effectively in teams, respect diverse perspectives, and achieve shared goals",
    displayOrder: 10,
    assessmentApplicable: true,
    relatedSubjects: null,
    version: "2025",
  },
  {
    name: "Curiosity",
    competencyType: "competency",
    category: "Character Qualities",
    description: "Intrinsic desire to explore, ask questions, and pursue lifelong learning",
    displayOrder: 11,
    assessmentApplicable: true,
    relatedSubjects: null,
    version: "2025",
  },
  {
    name: "Initiative",
    competencyType: "competency",
    category: "Character Qualities",
    description: "Ability to take proactive action, self-start, and drive projects forward independently",
    displayOrder: 12,
    assessmentApplicable: true,
    relatedSubjects: null,
    version: "2025",
  },
  {
    name: "Persistence and Grit",
    competencyType: "competency",
    category: "Character Qualities",
    description: "Determination to overcome obstacles, resilience in face of setbacks, and sustained effort toward long-term goals",
    displayOrder: 13,
    assessmentApplicable: true,
    relatedSubjects: null,
    version: "2025",
  },
  {
    name: "Adaptability",
    competencyType: "competency",
    category: "Character Qualities",
    description: "Flexibility to adjust to changing circumstances, embrace new situations, and learn from experiences",
    displayOrder: 14,
    assessmentApplicable: true,
    relatedSubjects: null,
    version: "2025",
  },
  {
    name: "Leadership",
    competencyType: "competency",
    category: "Social Skills",
    description: "Ability to inspire and guide others, take responsibility, and mobilize teams toward common objectives",
    displayOrder: 15,
    assessmentApplicable: true,
    relatedSubjects: null,
    version: "2025",
  },
  {
    name: "Social and Cultural Awareness",
    competencyType: "competency",
    category: "Social Skills",
    description: "Understanding of diverse perspectives, empathy for others, and awareness of social dynamics and cultural contexts",
    displayOrder: 16,
    assessmentApplicable: true,
    relatedSubjects: null,
    version: "2025",
  },
];

// Career-WEF Skill Affinity Mappings
// Scores represent 0-100 importance of each skill for the career
export const CAREER_WEF_SKILL_AFFINITIES: {
  careerTitle: string;
  skills: {
    [skillName: string]: number; // 0-100 affinity score
  };
}[] = [
  {
    careerTitle: "Software Engineer",
    skills: {
      "Literacy": 70,
      "Numeracy": 90,
      "Scientific Literacy": 60,
      "ICT Literacy": 100,
      "Financial Literacy": 40,
      "Cultural and Civic Literacy": 50,
      "Critical Thinking and Problem Solving": 95,
      "Creativity": 85,
      "Communication": 75,
      "Collaboration": 80,
      "Curiosity": 90,
      "Initiative": 85,
      "Persistence and Grit": 90,
      "Adaptability": 95,
      "Leadership": 70,
      "Social and Cultural Awareness": 60,
    },
  },
  {
    careerTitle: "Data Scientist",
    skills: {
      "Literacy": 75,
      "Numeracy": 100,
      "Scientific Literacy": 95,
      "ICT Literacy": 95,
      "Financial Literacy": 60,
      "Cultural and Civic Literacy": 50,
      "Critical Thinking and Problem Solving": 100,
      "Creativity": 85,
      "Communication": 80,
      "Collaboration": 75,
      "Curiosity": 95,
      "Initiative": 80,
      "Persistence and Grit": 90,
      "Adaptability": 90,
      "Leadership": 65,
      "Social and Cultural Awareness": 60,
    },
  },
  {
    careerTitle: "Renewable Energy Engineer",
    skills: {
      "Literacy": 70,
      "Numeracy": 90,
      "Scientific Literacy": 95,
      "ICT Literacy": 75,
      "Financial Literacy": 60,
      "Cultural and Civic Literacy": 70,
      "Critical Thinking and Problem Solving": 95,
      "Creativity": 85,
      "Communication": 70,
      "Collaboration": 80,
      "Curiosity": 85,
      "Initiative": 80,
      "Persistence and Grit": 90,
      "Adaptability": 85,
      "Leadership": 75,
      "Social and Cultural Awareness": 75,
    },
  },
  {
    careerTitle: "Healthcare Professional (Nurse)",
    skills: {
      "Literacy": 80,
      "Numeracy": 70,
      "Scientific Literacy": 85,
      "ICT Literacy": 60,
      "Financial Literacy": 40,
      "Cultural and Civic Literacy": 85,
      "Critical Thinking and Problem Solving": 90,
      "Creativity": 65,
      "Communication": 95,
      "Collaboration": 95,
      "Curiosity": 75,
      "Initiative": 85,
      "Persistence and Grit": 95,
      "Adaptability": 90,
      "Leadership": 75,
      "Social and Cultural Awareness": 95,
    },
  },
  {
    careerTitle: "Digital Marketing Specialist",
    skills: {
      "Literacy": 90,
      "Numeracy": 75,
      "Scientific Literacy": 50,
      "ICT Literacy": 95,
      "Financial Literacy": 70,
      "Cultural and Civic Literacy": 85,
      "Critical Thinking and Problem Solving": 85,
      "Creativity": 95,
      "Communication": 100,
      "Collaboration": 85,
      "Curiosity": 90,
      "Initiative": 90,
      "Persistence and Grit": 80,
      "Adaptability": 95,
      "Leadership": 75,
      "Social and Cultural Awareness": 90,
    },
  },
  {
    careerTitle: "Graphic Designer",
    skills: {
      "Literacy": 75,
      "Numeracy": 50,
      "Scientific Literacy": 40,
      "ICT Literacy": 90,
      "Financial Literacy": 55,
      "Cultural and Civic Literacy": 80,
      "Critical Thinking and Problem Solving": 75,
      "Creativity": 100,
      "Communication": 85,
      "Collaboration": 80,
      "Curiosity": 90,
      "Initiative": 85,
      "Persistence and Grit": 80,
      "Adaptability": 85,
      "Leadership": 60,
      "Social and Cultural Awareness": 85,
    },
  },
  {
    careerTitle: "Mechanical Engineer",
    skills: {
      "Literacy": 70,
      "Numeracy": 95,
      "Scientific Literacy": 95,
      "ICT Literacy": 80,
      "Financial Literacy": 55,
      "Cultural and Civic Literacy": 55,
      "Critical Thinking and Problem Solving": 95,
      "Creativity": 80,
      "Communication": 70,
      "Collaboration": 80,
      "Curiosity": 85,
      "Initiative": 80,
      "Persistence and Grit": 90,
      "Adaptability": 80,
      "Leadership": 70,
      "Social and Cultural Awareness": 60,
    },
  },
  {
    careerTitle: "Financial Analyst",
    skills: {
      "Literacy": 85,
      "Numeracy": 100,
      "Scientific Literacy": 60,
      "ICT Literacy": 85,
      "Financial Literacy": 100,
      "Cultural and Civic Literacy": 65,
      "Critical Thinking and Problem Solving": 95,
      "Creativity": 70,
      "Communication": 80,
      "Collaboration": 75,
      "Curiosity": 80,
      "Initiative": 85,
      "Persistence and Grit": 85,
      "Adaptability": 90,
      "Leadership": 75,
      "Social and Cultural Awareness": 70,
    },
  },
  {
    careerTitle: "Teacher (Secondary Education)",
    skills: {
      "Literacy": 95,
      "Numeracy": 80,
      "Scientific Literacy": 75,
      "ICT Literacy": 70,
      "Financial Literacy": 50,
      "Cultural and Civic Literacy": 90,
      "Critical Thinking and Problem Solving": 85,
      "Creativity": 85,
      "Communication": 100,
      "Collaboration": 90,
      "Curiosity": 90,
      "Initiative": 85,
      "Persistence and Grit": 95,
      "Adaptability": 95,
      "Leadership": 90,
      "Social and Cultural Awareness": 100,
    },
  },
  {
    careerTitle: "Environmental Scientist",
    skills: {
      "Literacy": 80,
      "Numeracy": 85,
      "Scientific Literacy": 100,
      "ICT Literacy": 75,
      "Financial Literacy": 55,
      "Cultural and Civic Literacy": 80,
      "Critical Thinking and Problem Solving": 95,
      "Creativity": 80,
      "Communication": 85,
      "Collaboration": 85,
      "Curiosity": 95,
      "Initiative": 85,
      "Persistence and Grit": 90,
      "Adaptability": 85,
      "Leadership": 75,
      "Social and Cultural Awareness": 85,
    },
  },
  // Continue with remaining 26 careers...
  {
    careerTitle: "Civil Engineer",
    skills: {
      "Literacy": 75,
      "Numeracy": 95,
      "Scientific Literacy": 90,
      "ICT Literacy": 80,
      "Financial Literacy": 70,
      "Cultural and Civic Literacy": 70,
      "Critical Thinking and Problem Solving": 95,
      "Creativity": 75,
      "Communication": 75,
      "Collaboration": 85,
      "Curiosity": 80,
      "Initiative": 80,
      "Persistence and Grit": 90,
      "Adaptability": 80,
      "Leadership": 80,
      "Social and Cultural Awareness": 70,
    },
  },
  {
    careerTitle: "Architect",
    skills: {
      "Literacy": 80,
      "Numeracy": 85,
      "Scientific Literacy": 75,
      "ICT Literacy": 85,
      "Financial Literacy": 70,
      "Cultural and Civic Literacy": 85,
      "Critical Thinking and Problem Solving": 90,
      "Creativity": 100,
      "Communication": 85,
      "Collaboration": 85,
      "Curiosity": 90,
      "Initiative": 85,
      "Persistence and Grit": 85,
      "Adaptability": 85,
      "Leadership": 80,
      "Social and Cultural Awareness": 90,
    },
  },
  {
    careerTitle: "Electrical Engineer",
    skills: {
      "Literacy": 70,
      "Numeracy": 95,
      "Scientific Literacy": 95,
      "ICT Literacy": 90,
      "Financial Literacy": 55,
      "Cultural and Civic Literacy": 55,
      "Critical Thinking and Problem Solving": 95,
      "Creativity": 80,
      "Communication": 70,
      "Collaboration": 80,
      "Curiosity": 85,
      "Initiative": 80,
      "Persistence and Grit": 90,
      "Adaptability": 85,
      "Leadership": 70,
      "Social and Cultural Awareness": 60,
    },
  },
  {
    careerTitle: "Biomedical Engineer",
    skills: {
      "Literacy": 75,
      "Numeracy": 95,
      "Scientific Literacy": 100,
      "ICT Literacy": 85,
      "Financial Literacy": 55,
      "Cultural and Civic Literacy": 65,
      "Critical Thinking and Problem Solving": 100,
      "Creativity": 85,
      "Communication": 75,
      "Collaboration": 85,
      "Curiosity": 95,
      "Initiative": 85,
      "Persistence and Grit": 95,
      "Adaptability": 90,
      "Leadership": 75,
      "Social and Cultural Awareness": 70,
    },
  },
  {
    careerTitle: "Pharmacist",
    skills: {
      "Literacy": 85,
      "Numeracy": 85,
      "Scientific Literacy": 95,
      "ICT Literacy": 65,
      "Financial Literacy": 60,
      "Cultural and Civic Literacy": 75,
      "Critical Thinking and Problem Solving": 90,
      "Creativity": 65,
      "Communication": 85,
      "Collaboration": 80,
      "Curiosity": 80,
      "Initiative": 80,
      "Persistence and Grit": 85,
      "Adaptability": 80,
      "Leadership": 70,
      "Social and Cultural Awareness": 85,
    },
  },
  {
    careerTitle: "Doctor (General Practitioner)",
    skills: {
      "Literacy": 90,
      "Numeracy": 80,
      "Scientific Literacy": 100,
      "ICT Literacy": 70,
      "Financial Literacy": 60,
      "Cultural and Civic Literacy": 85,
      "Critical Thinking and Problem Solving": 100,
      "Creativity": 70,
      "Communication": 95,
      "Collaboration": 90,
      "Curiosity": 95,
      "Initiative": 90,
      "Persistence and Grit": 100,
      "Adaptability": 95,
      "Leadership": 85,
      "Social and Cultural Awareness": 95,
    },
  },
  {
    careerTitle: "Dentist",
    skills: {
      "Literacy": 85,
      "Numeracy": 75,
      "Scientific Literacy": 90,
      "ICT Literacy": 65,
      "Financial Literacy": 70,
      "Cultural and Civic Literacy": 75,
      "Critical Thinking and Problem Solving": 90,
      "Creativity": 70,
      "Communication": 90,
      "Collaboration": 80,
      "Curiosity": 80,
      "Initiative": 85,
      "Persistence and Grit": 90,
      "Adaptability": 85,
      "Leadership": 75,
      "Social and Cultural Awareness": 85,
    },
  },
  {
    careerTitle: "Physical Therapist",
    skills: {
      "Literacy": 80,
      "Numeracy": 70,
      "Scientific Literacy": 85,
      "ICT Literacy": 60,
      "Financial Literacy": 50,
      "Cultural and Civic Literacy": 80,
      "Critical Thinking and Problem Solving": 85,
      "Creativity": 75,
      "Communication": 95,
      "Collaboration": 90,
      "Curiosity": 80,
      "Initiative": 85,
      "Persistence and Grit": 95,
      "Adaptability": 90,
      "Leadership": 75,
      "Social and Cultural Awareness": 90,
    },
  },
  {
    careerTitle: "Psychologist",
    skills: {
      "Literacy": 95,
      "Numeracy": 70,
      "Scientific Literacy": 85,
      "ICT Literacy": 60,
      "Financial Literacy": 50,
      "Cultural and Civic Literacy": 95,
      "Critical Thinking and Problem Solving": 95,
      "Creativity": 80,
      "Communication": 100,
      "Collaboration": 85,
      "Curiosity": 95,
      "Initiative": 85,
      "Persistence and Grit": 90,
      "Adaptability": 95,
      "Leadership": 75,
      "Social and Cultural Awareness": 100,
    },
  },
  {
    careerTitle: "Social Worker",
    skills: {
      "Literacy": 85,
      "Numeracy": 60,
      "Scientific Literacy": 65,
      "ICT Literacy": 60,
      "Financial Literacy": 55,
      "Cultural and Civic Literacy": 100,
      "Critical Thinking and Problem Solving": 85,
      "Creativity": 75,
      "Communication": 100,
      "Collaboration": 95,
      "Curiosity": 80,
      "Initiative": 90,
      "Persistence and Grit": 95,
      "Adaptability": 95,
      "Leadership": 80,
      "Social and Cultural Awareness": 100,
    },
  },
  {
    careerTitle: "Lawyer",
    skills: {
      "Literacy": 100,
      "Numeracy": 70,
      "Scientific Literacy": 55,
      "ICT Literacy": 70,
      "Financial Literacy": 75,
      "Cultural and Civic Literacy": 95,
      "Critical Thinking and Problem Solving": 100,
      "Creativity": 75,
      "Communication": 100,
      "Collaboration": 80,
      "Curiosity": 85,
      "Initiative": 90,
      "Persistence and Grit": 95,
      "Adaptability": 85,
      "Leadership": 85,
      "Social and Cultural Awareness": 90,
    },
  },
  {
    careerTitle: "Accountant",
    skills: {
      "Literacy": 80,
      "Numeracy": 100,
      "Scientific Literacy": 50,
      "ICT Literacy": 85,
      "Financial Literacy": 100,
      "Cultural and Civic Literacy": 60,
      "Critical Thinking and Problem Solving": 90,
      "Creativity": 60,
      "Communication": 75,
      "Collaboration": 75,
      "Curiosity": 70,
      "Initiative": 80,
      "Persistence and Grit": 90,
      "Adaptability": 80,
      "Leadership": 65,
      "Social and Cultural Awareness": 65,
    },
  },
  {
    careerTitle: "Human Resources Manager",
    skills: {
      "Literacy": 90,
      "Numeracy": 65,
      "Scientific Literacy": 50,
      "ICT Literacy": 75,
      "Financial Literacy": 70,
      "Cultural and Civic Literacy": 90,
      "Critical Thinking and Problem Solving": 85,
      "Creativity": 75,
      "Communication": 100,
      "Collaboration": 95,
      "Curiosity": 80,
      "Initiative": 90,
      "Persistence and Grit": 85,
      "Adaptability": 95,
      "Leadership": 95,
      "Social and Cultural Awareness": 100,
    },
  },
  {
    careerTitle: "Management Consultant",
    skills: {
      "Literacy": 90,
      "Numeracy": 85,
      "Scientific Literacy": 60,
      "ICT Literacy": 80,
      "Financial Literacy": 90,
      "Cultural and Civic Literacy": 80,
      "Critical Thinking and Problem Solving": 100,
      "Creativity": 85,
      "Communication": 95,
      "Collaboration": 90,
      "Curiosity": 90,
      "Initiative": 95,
      "Persistence and Grit": 90,
      "Adaptability": 100,
      "Leadership": 95,
      "Social and Cultural Awareness": 85,
    },
  },
  {
    careerTitle: "Entrepreneur",
    skills: {
      "Literacy": 85,
      "Numeracy": 80,
      "Scientific Literacy": 60,
      "ICT Literacy": 80,
      "Financial Literacy": 95,
      "Cultural and Civic Literacy": 80,
      "Critical Thinking and Problem Solving": 95,
      "Creativity": 100,
      "Communication": 95,
      "Collaboration": 85,
      "Curiosity": 100,
      "Initiative": 100,
      "Persistence and Grit": 100,
      "Adaptability": 100,
      "Leadership": 100,
      "Social and Cultural Awareness": 85,
    },
  },
  {
    careerTitle: "Sales Manager",
    skills: {
      "Literacy": 85,
      "Numeracy": 75,
      "Scientific Literacy": 45,
      "ICT Literacy": 70,
      "Financial Literacy": 80,
      "Cultural and Civic Literacy": 80,
      "Critical Thinking and Problem Solving": 85,
      "Creativity": 80,
      "Communication": 100,
      "Collaboration": 90,
      "Curiosity": 85,
      "Initiative": 95,
      "Persistence and Grit": 95,
      "Adaptability": 95,
      "Leadership": 95,
      "Social and Cultural Awareness": 90,
    },
  },
  {
    careerTitle: "Marketing Manager",
    skills: {
      "Literacy": 90,
      "Numeracy": 75,
      "Scientific Literacy": 50,
      "ICT Literacy": 85,
      "Financial Literacy": 75,
      "Cultural and Civic Literacy": 90,
      "Critical Thinking and Problem Solving": 90,
      "Creativity": 95,
      "Communication": 100,
      "Collaboration": 90,
      "Curiosity": 90,
      "Initiative": 90,
      "Persistence and Grit": 85,
      "Adaptability": 95,
      "Leadership": 90,
      "Social and Cultural Awareness": 95,
    },
  },
  {
    careerTitle: "Product Manager",
    skills: {
      "Literacy": 85,
      "Numeracy": 80,
      "Scientific Literacy": 70,
      "ICT Literacy": 90,
      "Financial Literacy": 80,
      "Cultural and Civic Literacy": 75,
      "Critical Thinking and Problem Solving": 95,
      "Creativity": 90,
      "Communication": 95,
      "Collaboration": 95,
      "Curiosity": 95,
      "Initiative": 95,
      "Persistence and Grit": 90,
      "Adaptability": 100,
      "Leadership": 95,
      "Social and Cultural Awareness": 85,
    },
  },
  {
    careerTitle: "UX/UI Designer",
    skills: {
      "Literacy": 80,
      "Numeracy": 60,
      "Scientific Literacy": 55,
      "ICT Literacy": 95,
      "Financial Literacy": 55,
      "Cultural and Civic Literacy": 85,
      "Critical Thinking and Problem Solving": 90,
      "Creativity": 100,
      "Communication": 90,
      "Collaboration": 90,
      "Curiosity": 95,
      "Initiative": 85,
      "Persistence and Grit": 80,
      "Adaptability": 95,
      "Leadership": 70,
      "Social and Cultural Awareness": 95,
    },
  },
  {
    careerTitle: "Video Game Designer",
    skills: {
      "Literacy": 75,
      "Numeracy": 70,
      "Scientific Literacy": 60,
      "ICT Literacy": 95,
      "Financial Literacy": 55,
      "Cultural and Civic Literacy": 75,
      "Critical Thinking and Problem Solving": 90,
      "Creativity": 100,
      "Communication": 80,
      "Collaboration": 90,
      "Curiosity": 100,
      "Initiative": 85,
      "Persistence and Grit": 90,
      "Adaptability": 90,
      "Leadership": 70,
      "Social and Cultural Awareness": 80,
    },
  },
  {
    careerTitle: "Journalist",
    skills: {
      "Literacy": 100,
      "Numeracy": 60,
      "Scientific Literacy": 65,
      "ICT Literacy": 80,
      "Financial Literacy": 60,
      "Cultural and Civic Literacy": 100,
      "Critical Thinking and Problem Solving": 95,
      "Creativity": 90,
      "Communication": 100,
      "Collaboration": 85,
      "Curiosity": 100,
      "Initiative": 95,
      "Persistence and Grit": 95,
      "Adaptability": 95,
      "Leadership": 75,
      "Social and Cultural Awareness": 100,
    },
  },
  {
    careerTitle: "Content Creator",
    skills: {
      "Literacy": 90,
      "Numeracy": 55,
      "Scientific Literacy": 50,
      "ICT Literacy": 95,
      "Financial Literacy": 65,
      "Cultural and Civic Literacy": 85,
      "Critical Thinking and Problem Solving": 80,
      "Creativity": 100,
      "Communication": 100,
      "Collaboration": 80,
      "Curiosity": 95,
      "Initiative": 100,
      "Persistence and Grit": 90,
      "Adaptability": 100,
      "Leadership": 75,
      "Social and Cultural Awareness": 90,
    },
  },
  {
    careerTitle: "Photographer",
    skills: {
      "Literacy": 70,
      "Numeracy": 55,
      "Scientific Literacy": 50,
      "ICT Literacy": 85,
      "Financial Literacy": 65,
      "Cultural and Civic Literacy": 80,
      "Critical Thinking and Problem Solving": 75,
      "Creativity": 100,
      "Communication": 80,
      "Collaboration": 75,
      "Curiosity": 90,
      "Initiative": 90,
      "Persistence and Grit": 85,
      "Adaptability": 85,
      "Leadership": 65,
      "Social and Cultural Awareness": 85,
    },
  },
  {
    careerTitle: "Chef",
    skills: {
      "Literacy": 70,
      "Numeracy": 65,
      "Scientific Literacy": 60,
      "ICT Literacy": 50,
      "Financial Literacy": 70,
      "Cultural and Civic Literacy": 85,
      "Critical Thinking and Problem Solving": 80,
      "Creativity": 100,
      "Communication": 80,
      "Collaboration": 85,
      "Curiosity": 90,
      "Initiative": 90,
      "Persistence and Grit": 95,
      "Adaptability": 90,
      "Leadership": 85,
      "Social and Cultural Awareness": 90,
    },
  },
  {
    careerTitle: "Fashion Designer",
    skills: {
      "Literacy": 75,
      "Numeracy": 60,
      "Scientific Literacy": 50,
      "ICT Literacy": 75,
      "Financial Literacy": 70,
      "Cultural and Civic Literacy": 95,
      "Critical Thinking and Problem Solving": 80,
      "Creativity": 100,
      "Communication": 85,
      "Collaboration": 80,
      "Curiosity": 95,
      "Initiative": 90,
      "Persistence and Grit": 85,
      "Adaptability": 90,
      "Leadership": 75,
      "Social and Cultural Awareness": 100,
    },
  },
  {
    careerTitle: "Interior Designer",
    skills: {
      "Literacy": 75,
      "Numeracy": 70,
      "Scientific Literacy": 55,
      "ICT Literacy": 80,
      "Financial Literacy": 75,
      "Cultural and Civic Literacy": 90,
      "Critical Thinking and Problem Solving": 85,
      "Creativity": 100,
      "Communication": 90,
      "Collaboration": 90,
      "Curiosity": 90,
      "Initiative": 85,
      "Persistence and Grit": 85,
      "Adaptability": 90,
      "Leadership": 75,
      "Social and Cultural Awareness": 95,
    },
  },
];
