import type { Assessment, Career } from "@shared/schema";
import type { RiasecScores } from "./matching";

/**
 * Premium Narrative Generator
 * Generates enhanced, personalized career insights for premium-tier assessments
 * using RIASEC personality and CVQ values data.
 *
 * Supports English (default) and Arabic output via the `language` field in
 * NarrativeContext.  The "Why This Career?" (premiumReasoning) section is
 * generated by the LLM pipeline when an API key is configured; these heuristic
 * functions serve as the fallback and as the primary source for workStyleFit,
 * strengthsGrowth, and enhancedActionSteps.
 */

interface NarrativeContext {
  assessment: Assessment;
  career: Career;
  riasecScores?: RiasecScores;
  cvqScores?: Record<string, any>;
  overallScore: number;
  language?: string;
}

// ===== Small helpers =====

function matchQuality(score: number, lang: string): string {
  if (lang === "ar") {
    if (score >= 80) return "متوافق للغاية";
    if (score >= 70) return "متوافق بشكل قوي";
    return "متوافق بشكل جيد";
  }
  if (score >= 80) return "highly compatible";
  if (score >= 70) return "strong";
  return "good";
}

/** Return the career's localised title, falling back to the English title. */
function localTitle(career: Career, lang: string): string {
  return lang === "ar" && career.titleAr ? career.titleAr : career.title;
}

// ===== RIASEC descriptions =====

function getRiasecThemeDescription(code: string, lang: string): string {
  const en: Record<string, string> = {
    R: "You have a Realistic personality—you prefer hands-on work and practical problem-solving",
    I: "You have an Investigative personality—you enjoy analyzing data and solving complex problems",
    A: "You have an Artistic personality—you value creativity and self-expression",
    S: "You have a Social personality—you thrive on helping others and building relationships",
    E: "You have an Enterprising personality—you enjoy leading projects and persuading others",
    C: "You have a Conventional personality—you excel at organization and attention to detail",
  };
  const ar: Record<string, string> = {
    R: "لديك شخصية واقعية — تفضل العمل العملي وحل المشكلات التطبيقية",
    I: "لديك شخصية استقصائية — تستمتع بتحليل البيانات وحل المشكلات المعقدة",
    A: "لديك شخصية فنية — تقدّر الإبداع والتعبير الذاتي",
    S: "لديك شخصية اجتماعية — تزدهر في مساعدة الآخرين وبناء العلاقات",
    E: "لديك شخصية مغامِرة — تستمتع بقيادة المشاريع وإقناع الآخرين",
    C: "لديك شخصية تقليدية — تتميز في التنظيم والاهتمام بالتفاصيل",
  };
  return (lang === "ar" ? ar : en)[code] ?? "";
}

function getRiasecCareerFit(code: string, title: string, lang: string): string {
  if (lang === "ar") {
    const ar: Record<string, string> = {
      R: `تتضمن وظائف ${title} في الغالب نتائج ملموسة ومهارات تقنية تتناسب مع طبيعتك العملية`,
      I: `يتطلب مجال ${title} التفكير التحليلي ومهارات البحث التي تُحفزك وتشحن طاقتك`,
      A: `يُتيح لك مجال ${title} فرصاً لحل المشكلات بإبداع والتفكير الابتكاري الذي يُشغّل عقلك الفني`,
      S: `يتضمن مجال ${title} تفاعلات ذات معنى ومساعدة الآخرين، وهو ما يتوافق تماماً مع طبيعتك الاجتماعية`,
      E: `يُوفر مجال ${title} فرص قيادة والقدرة على قيادة المبادرات، مما يتناسب مع روحك الريادية`,
      C: `يُقدّر مجال ${title} الأسلوب المنظم والعمل الدقيق الذي تتفوق فيه بشكل طبيعي`,
    };
    return ar[code] ?? `يتوافق مجال ${title} مع نقاط قوتك ومهاراتك`;
  }
  const en: Record<string, string> = {
    R: `${title} roles often involve tangible outcomes and technical skills that match your practical nature`,
    I: `${title} requires the analytical thinking and research skills that energize you`,
    A: `${title} provides opportunities for creative problem-solving and innovative thinking that engage your artistic mindset`,
    S: `${title} involves meaningful interactions and helping others, which aligns perfectly with your people-oriented nature`,
    E: `${title} offers leadership opportunities and the chance to drive initiatives, matching your entrepreneurial spirit`,
    C: `${title} values the structured approach and precise work that you naturally excel at`,
  };
  return en[code] ?? `${title} aligns with your strengths and skills`;
}

// ===== Values descriptions =====

function getValueDescription(value: string, lang: string): string {
  const en: Record<string, string> = {
    achievement: "success and personal accomplishment",
    benevolence: "helping others and making a positive impact",
    universalism: "fairness, equality, and social justice",
    self_direction: "independence and creative freedom",
    security: "stability and safety",
    power: "influence and leadership",
    hedonism: "enjoyment and work-life balance",
  };
  const ar: Record<string, string> = {
    achievement: "النجاح والإنجاز الشخصي",
    benevolence: "مساعدة الآخرين وإحداث أثر إيجابي",
    universalism: "العدل والمساواة والعدالة الاجتماعية",
    self_direction: "الاستقلالية والحرية الإبداعية",
    security: "الاستقرار والأمان",
    power: "التأثير والقيادة",
    hedonism: "الاستمتاع بالحياة والتوازن بين العمل والحياة",
  };
  return (lang === "ar" ? ar : en)[value] ?? value;
}

function getValueCareerAlignment(value: string, title: string, lang: string): string {
  if (lang === "ar") {
    const ar: Record<string, string> = {
      achievement: `يُوفر مجال ${title} معايير واضحة للنجاح وفرصاً لإثبات كفاءتك من خلال نتائج قابلة للقياس`,
      benevolence: `يُتيح لك مجال ${title} المساهمة بشكل هادف في حياة الآخرين وإحداث فرق ملموس في مجتمعك`,
      universalism: `يُوفر مجال ${title} فرصاً للترويج للعدل والمساهمة في بناء مجتمع أكثر إنصافاً`,
      self_direction: `يُتيح لك مجال ${title} الاستقلالية في اتخاذ القرار وحيزاً لحل المشكلات بإبداع`,
      security: `يُوفر مجال ${title} آفاقاً مهنية مستقرة ومسارات واضحة وظروف عمل موثوقة`,
      power: `يُوفر مجال ${title} فرصاً لتولي أدوار قيادية والتأثير في القرارات المهمة في مجالك`,
      hedonism: `يُمكن أن يُوفر مجال ${title} توازناً بين العمل والحياة ومرونة للاستمتاع بالحياة أثناء بناء مسيرة مهنية مُرضية`,
    };
    return ar[value] ?? `يتوافق مجال ${title} مع قيمك`;
  }
  const en: Record<string, string> = {
    achievement: `${title} provides clear benchmarks for success and opportunities to demonstrate your competence through measurable results`,
    benevolence: `${title} allows you to contribute meaningfully to others' lives and make a tangible difference in your community`,
    universalism: `${title} offers opportunities to promote fairness and contribute to creating a more just and equitable society`,
    self_direction: `${title} provides autonomy in decision-making and room for creative problem-solving that respects your independence`,
    security: `${title} offers stable career prospects with clear professional pathways and reliable working conditions`,
    power: `${title} provides opportunities to take on leadership roles and influence important decisions in your field`,
    hedonism: `${title} can offer work-life balance and the flexibility to enjoy life while building a fulfilling career`,
  };
  return en[value] ?? `aligns with your values`;
}

// ===== Collaboration styles =====

function getRiasecCollaborationStyle(theme: string, lang: string): string {
  const en: Record<string, string> = {
    R: "You work well independently or in small technical teams where roles are clearly defined and communication is direct and practical.",
    I: "You thrive in collaborative environments where ideas are debated intellectually, and team members value evidence-based decision-making.",
    A: "You excel in creative teams that encourage brainstorming, value diverse perspectives, and allow for individual expression within group projects.",
    S: "You're a natural team player who builds strong relationships, facilitates group harmony, and helps bring out the best in your colleagues.",
    E: "You naturally take leadership roles, enjoy coordinating team efforts, and excel at motivating others toward shared goals.",
    C: "You contribute best in structured teams with clear procedures, where your organizational skills and attention to detail keep projects on track.",
  };
  const ar: Record<string, string> = {
    R: "تعمل بشكل جيد بمفردك أو في فرق تقنية صغيرة حيث تكون الأدوار محددة بوضوح والتواصل مباشراً وعملياً.",
    I: "تزدهر في بيئات تعاونية يتم فيها نقاش الأفكار فكرياً، وتُقدّر فيها القرارات المبنية على الأدلة.",
    A: "تتميز في الفرق الإبداعية التي تشجع العصف الذهني وتُقدّر وجهات النظر المتنوعة وتُتيح التعبير الفردي.",
    S: "أنت لاعب فريق طبيعي تبني علاقات قوية وتُيسّر الانسجام الجماعي وتساعد في إبراز أفضل ما في زملائك.",
    E: "تتولى أدوار قيادية بشكل طبيعي وتستمتع بتنسيق جهود الفريق والتميز في تحفيز الآخرين نحو الأهداف المشتركة.",
    C: "تُسهم بشكل أفضل في فرق منظمة ذات إجراءات واضحة حيث تُبقي مهاراتك التنظيمية واهتمامك بالتفاصيل المشاريع على المسار الصحيح.",
  };
  return (lang === "ar" ? ar : en)[theme] ?? (
    lang === "ar"
      ? "تتكيف بشكل جيد مع مختلف هياكل الفريق."
      : "You adapt well to various team structures and collaboration styles."
  );
}

function getRiasecTaskPreferences(theme: string, title: string, lang: string): string {
  if (lang === "ar") {
    const ar: Record<string, string> = {
      R: `بوصفك ${title}، ستستمتع بمهام مثل بناء النماذج الأولية وحل المشكلات التقنية والعمل مع الأدوات أو المعدات — وهي جميعها تتوافق مع تفضيلاتك العملية.`,
      I: `قد يشمل يومك المعتاد تحليل البيانات والبحث عن حلول للمشكلات المعقدة ووضع توصيات مبنية على أدلة — مهام تُشبع فضولك الفكري.`,
      A: `ستنجذب إلى المهام التي تنطوي على التصميم الإبداعي وتطوير حلول مبتكرة وصياغة عروض تقديمية مقنعة — عمل يُشغّل حواسك الفنية.`,
      S: `قد يتضمن يوم عملك تدريب الآخرين وتيسير اجتماعات الفريق وبناء علاقات مع أصحاب المصلحة — أنشطة تستثمر نقاط قوتك في التواصل الإنساني.`,
      E: `ستزدهر في مهام مثل تقديم الأفكار وقيادة فرق المشاريع والتفاوض مع الشركاء — عمل يستخدم قدراتك في الإقناع والقيادة.`,
      C: `سيتضمن يومك على الأرجح تنظيم الأنظمة وضمان الجودة والحفاظ على سجلات دقيقة — مهام تستثمر مهاراتك التنظيمية الاستثنائية.`,
    };
    return ar[theme] ?? `ستُشغّل مهامك اليومية كـ${title} نقاط قوتك واهتماماتك الطبيعية.`;
  }
  const en: Record<string, string> = {
    R: `As a ${title}, you'll enjoy tasks like building prototypes, troubleshooting technical issues, and working with tools or equipment—all of which align with your practical, hands-on preferences.`,
    I: `Your typical day might include analyzing data, researching solutions to complex problems, and developing evidence-based recommendations—tasks that satisfy your intellectual curiosity.`,
    A: `You'll gravitate toward tasks that involve creative design, developing innovative solutions, and crafting compelling presentations—work that engages your artistic sensibilities.`,
    S: `Your workday might involve mentoring others, facilitating team meetings, and building stakeholder relationships—activities that leverage your interpersonal strengths.`,
    E: `You'll thrive on tasks like pitching ideas, leading project teams, and negotiating with partners—work that uses your persuasive and leadership abilities.`,
    C: `Your day will likely include organizing systems, ensuring quality control, and maintaining detailed records—tasks that utilize your exceptional organizational skills.`,
  };
  return en[theme] ?? `Your daily tasks in ${title} will engage your natural strengths and interests.`;
}

// ===== Strengths =====

function getRiasecStrength(theme: string, lang: string): string {
  const en: Record<string, string> = {
    R: "Practical problem-solving and hands-on technical skills—you can troubleshoot issues and create tangible solutions",
    I: "Analytical thinking and research abilities—you excel at gathering information and drawing logical conclusions",
    A: "Creative innovation and original thinking—you bring fresh perspectives and imaginative solutions to challenges",
    S: "Interpersonal skills and empathy—you understand people's needs and build strong, supportive relationships",
    E: "Leadership and persuasion—you can motivate others and drive initiatives forward with confidence",
    C: "Organization and attention to detail—you create order from complexity and ensure accuracy in your work",
  };
  const ar: Record<string, string> = {
    R: "حل المشكلات عملياً والمهارات التقنية التطبيقية — تستطيع معالجة المشكلات وإيجاد حلول ملموسة",
    I: "التفكير التحليلي وقدرات البحث — تتميز في جمع المعلومات واستخلاص استنتاجات منطقية",
    A: "الابتكار الإبداعي والتفكير الأصيل — تُقدّم وجهات نظر جديدة وحلولاً خيالية للتحديات",
    S: "المهارات الإنسانية والتعاطف — تفهم احتياجات الناس وتبني علاقات قوية وداعمة",
    E: "القيادة والإقناع — تستطيع تحفيز الآخرين وقيادة المبادرات بثقة",
    C: "التنظيم والاهتمام بالتفاصيل — تُنشئ النظام من الفوضى وتضمن الدقة في عملك",
  };
  return (lang === "ar" ? ar : en)[theme] ?? (
    lang === "ar" ? "قدرات مهنية قوية" : "Strong professional capabilities"
  );
}

// ===== Growth areas =====

function getValueGrowthArea(lowestValue: string, lang: string): string {
  const en: Record<string, string> = {
    achievement: "Consider setting specific professional goals to channel your strengths into measurable accomplishments and build confidence through visible successes.",
    benevolence: "Explore volunteer opportunities or mentoring roles to develop your capacity for helping others—a skill that enhances leadership and teamwork.",
    universalism: "Engage with diverse perspectives and communities to develop broader understanding of social issues and build cultural competence.",
    self_direction: "Practice making independent decisions in low-stakes situations to build confidence in your autonomous thinking and creative problem-solving.",
    security: "Develop contingency planning skills and financial literacy to build a stronger foundation for long-term stability and risk management.",
    power: "Seek leadership opportunities in clubs or projects to develop your influence skills and comfort with authority and decision-making.",
    hedonism: "Remember to prioritize self-care and work-life balance—sustainable performance requires time for rest and enjoyment.",
  };
  const ar: Record<string, string> = {
    achievement: "فكر في وضع أهداف مهنية محددة لتوجيه نقاط قوتك نحو إنجازات قابلة للقياس وبناء الثقة من خلال النجاحات الملموسة.",
    benevolence: "استكشف فرص التطوع أو أدوار الإرشاد لتطوير قدرتك على مساعدة الآخرين — وهي مهارة تُعزز القيادة والعمل الجماعي.",
    universalism: "تفاعل مع وجهات نظر ومجتمعات متنوعة لتطوير فهم أعمق للقضايا الاجتماعية وبناء الكفاءة الثقافية.",
    self_direction: "تدرّب على اتخاذ قرارات مستقلة في مواقف منخفضة المخاطر لبناء الثقة في تفكيرك المستقل وحل المشكلات بإبداع.",
    security: "طوّر مهارات التخطيط للطوارئ والثقافة المالية لبناء أساس أقوى للاستقرار طويل الأمد وإدارة المخاطر.",
    power: "ابحث عن فرص قيادية في الأندية أو المشاريع لتطوير مهاراتك التأثيرية وراحتك مع السلطة واتخاذ القرار.",
    hedonism: "تذكر أن تُولي الأولوية لرعاية الذات والتوازن بين العمل والحياة — فالأداء المستدام يتطلب وقتاً للراحة والاستمتاع.",
  };
  return (lang === "ar" ? ar : en)[lowestValue] ?? (
    lang === "ar"
      ? "واصل تطوير مجموعة متوازنة من القيم الشخصية."
      : "Continue developing a balanced set of personal values."
  );
}

// ===== Helper =====

function getTopRiasecThemes(scores: RiasecScores): string[] {
  return (["R", "I", "A", "S", "E", "C"] as const)
    .map((code) => ({ code, score: scores[code] }))
    .sort((a, b) => b.score - a.score)
    .map((t) => t.code)
    .slice(0, 3);
}

// ===== Exported narrative generators =====

/**
 * Generate expanded "Why This Career?" reasoning (5-6 paragraphs).
 * Used as the heuristic fallback when the LLM service is unavailable.
 */
export function generateEnhancedReasoning(context: NarrativeContext): string {
  const { assessment, career, riasecScores, cvqScores, overallScore, language = "en" } = context;
  const lang = language === "ar" ? "ar" : "en";
  const title = localTitle(career, lang);
  const paragraphs: string[] = [];

  // Paragraph 1: Overall match introduction
  if (lang === "ar") {
    paragraphs.push(
      `يُعدّ مجال ${title} تطابقاً ${matchQuality(overallScore, lang)} لك، بنسبة ${overallScore.toFixed(1)}% بناءً على تقييمك الشامل. يتوافق هذا المجال المهني مع مزيجك الفريد من الاهتمامات وسمات الشخصية والقيم الشخصية.`
    );
  } else {
    paragraphs.push(
      `${title} is a ${matchQuality(overallScore, lang)} match for you, scoring ${overallScore.toFixed(1)}% based on your comprehensive assessment. This career aligns with your unique combination of interests, personality traits, and personal values.`
    );
  }

  // Paragraph 2: RIASEC personality match
  if (riasecScores) {
    const primary = getTopRiasecThemes(riasecScores)[0];
    const desc = getRiasecThemeDescription(primary, lang);
    const fit = getRiasecCareerFit(primary, title, lang);
    if (lang === "ar") {
      paragraphs.push(`${desc}. ${fit}. يُشير ملفك الشخصي إلى أنك ستجد هذا العمل مثيراً للاهتمام ومُرضياً بشكل طبيعي.`);
    } else {
      paragraphs.push(`${desc}. ${fit}. Your personality profile suggests you'll find this work naturally engaging and fulfilling.`);
    }
  }

  // Paragraph 3: Values alignment (CVQ)
  if (cvqScores?.top3 && Array.isArray(cvqScores.top3)) {
    const primary = cvqScores.top3[0] as string;
    const primaryDesc = getValueDescription(primary, lang);
    const alignment = getValueCareerAlignment(primary, title, lang);
    if (lang === "ar") {
      paragraphs.push(`ما يهمك أكثر — ${primaryDesc} — ينعكس في هذا الاختيار المهني. ${alignment}. هذا التوافق في القيم يعني أنك أكثر احتمالاً لإيجاد الرضا والمعنى على المدى البعيد في عملك.`);
    } else {
      paragraphs.push(`What matters most to you—${primaryDesc}—is reflected in this career choice. ${alignment}. This values alignment means you're more likely to find long-term satisfaction and meaning in your work.`);
    }
  }

  // Paragraph 4: Subject & skills connection
  if (assessment.favoriteSubjects) {
    const subjects = assessment.favoriteSubjects as string[];
    const relevantSubjects = subjects.filter((s) => career.relatedSubjects.includes(s));
    if (relevantSubjects.length === 0) {
      paragraphs.push(
        lang === "ar"
          ? `المهارات التحليلية وحل المشكلات التي تطورها في دراستك ستنتقل بشكل جيد إلى مجال ${title}.`
          : `The analytical and problem-solving skills you're developing in your coursework will transfer well to ${title}.`
      );
    } else {
      const subjectList = relevantSubjects.slice(0, 3).join(lang === "ar" ? " و" : ", ");
      paragraphs.push(
        lang === "ar"
          ? `اهتمامك بـ${subjectList} يدعم مسار هذه المهنة مباشرةً. تُشكّل المفاهيم والمهارات من هذه المواد الأساس لعمل ${title}. مع تقدمك، ستدرك كيف تنطبق المعرفة الأكاديمية على التحديات المهنية الواقعية، مما يجعل دراستك أكثر هدفاً وجاذبية.`
          : `Your interest in ${subjectList} directly supports this career path. The concepts and skills from these subjects form the foundation for ${title} work. As you advance, you'll see how classroom knowledge applies to real-world professional challenges, making your studies more purposeful and engaging.`
      );
    }
  }

  // Paragraph 5: Future outlook
  const skills = career.requiredSkills.slice(0, 3).join(lang === "ar" ? " و" : ", ");
  paragraphs.push(
    lang === "ar"
      ? `وبالنظر إلى المستقبل، يُوفر مجال ${title} إمكانات نمو قوية في سوق العمل الإماراتي. المهارات التي ستطورها — بما فيها ${skills} — تكتسب قيمة متزايدة مع تحديث الصناعات. يُتيح هذا المسار المهني فرصاً للتعلم المستمر والتقدم المهني المتوافق مع نقاط قوتك.`
      : `Looking ahead, ${title} offers strong growth potential in the UAE job market. The skills you'll develop—including ${skills}—are increasingly valuable as industries modernize. This career path provides opportunities for continuous learning and professional advancement aligned with your strengths.`
  );

  return paragraphs.join("\n\n");
}

/**
 * Generate "Your Work Style Fit" section.
 */
export function generateWorkStyleFit(context: NarrativeContext): string {
  const { career, riasecScores, language = "en" } = context;
  const lang = language === "ar" ? "ar" : "en";
  const title = localTitle(career, lang);
  const sections: string[] = [];

  if (riasecScores) {
    const topTheme = getTopRiasecThemes(riasecScores)[0];
    const collaborationLabel = lang === "ar" ? "**أسلوب التعاون الجماعي:**" : "**Team Collaboration:**";
    sections.push(`${collaborationLabel} ${getRiasecCollaborationStyle(topTheme, lang)}`);

    const tasksLabel = lang === "ar" ? "**المهام اليومية:**" : "**Daily Tasks:**";
    sections.push(`${tasksLabel} ${getRiasecTaskPreferences(topTheme, title, lang)}`);
  }

  return sections.join("\n\n");
}

/**
 * Generate "Personal Strengths & Growth Areas" section.
 */
export function generateStrengthsGrowth(context: NarrativeContext): string {
  const { riasecScores, cvqScores, language = "en" } = context;
  const lang = language === "ar" ? "ar" : "en";
  const sections: string[] = [];

  const strengths: string[] = [];
  if (riasecScores) {
    getTopRiasecThemes(riasecScores)
      .slice(0, 2)
      .forEach((theme) => strengths.push(getRiasecStrength(theme, lang)));
  }
  if (strengths.length > 0) {
    const label = lang === "ar" ? "**نقاط قوتك الأساسية:**" : "**Your Core Strengths:**";
    sections.push(`${label}\n${strengths.map((s, i) => `${i + 1}. ${s}`).join("\n")}`);
  }

  const growthAreas: string[] = [];
  if (cvqScores?.top3) {
    const lowestValue = (cvqScores.top3 as string[]).at(-1);
    if (lowestValue) growthAreas.push(getValueGrowthArea(lowestValue, lang));
  }
  if (growthAreas.length > 0) {
    const label = lang === "ar" ? "**مجالات النمو:**" : "**Areas for Growth:**";
    sections.push(`${label}\n${growthAreas.map((g, i) => `${i + 1}. ${g}`).join("\n")}`);
  }

  return sections.join("\n\n");
}

/**
 * Generate enhanced action steps (7 detailed steps with timelines).
 */
export function generateEnhancedActionSteps(context: NarrativeContext): string[] {
  const { assessment, career, language = "en" } = context;
  const lang = language === "ar" ? "ar" : "en";
  const title = localTitle(career, lang);
  const skills01 = career.requiredSkills.slice(0, 2).join(lang === "ar" ? " و" : " and ");
  const steps: string[] = [];

  if (lang === "ar") {
    steps.push(`**هذا الشهر:** ابحث في مجال ${title} من خلال مشاهدة مقاطع فيديو عن يوم في حياة المهنيين وقراءة ملفاتهم الشخصية لفهم المسؤوليات اليومية`);
    steps.push(`**خلال 3 أشهر:** تواصل مع محترف في مجال ${title} لإجراء مقابلة معلوماتية مدتها 20 دقيقة للتعرف على مسيرته المهنية ونصائحه`);

    if (assessment.favoriteSubjects && (assessment.favoriteSubjects as string[]).length > 0) {
      const topSubject = (assessment.favoriteSubjects as string[])[0];
      steps.push(`**خلال 6 أشهر:** تفوق في مادة ${topSubject} من خلال السعي للقيام بمشاريع متقدمة أو مسابقات لبناء المعرفة الأساسية لهذه المهنة`);
    }

    steps.push(`**خلال سنة:** ابدأ بتطوير مهارات أساسية مثل ${skills01} من خلال الدورات الإلكترونية أو الأنشطة المدرسية أو المشاريع الشخصية`);
    steps.push(`**السنتان 2-3:** اكتسب خبرة عملية من خلال التدريب الميداني أو العمل التطوعي أو الفرص بدوام جزئي في مجال ${career.category} لبناء سيرتك الذاتية وشبكة علاقاتك`);
    steps.push(`**السنة 3-4:** ابحث في الجامعات التي تُقدم برامج قوية في مجال ${career.category} وقدّم طلباتك، مع التركيز على المؤسسات ذات الروابط الصناعية والتدريب العملي`);
    steps.push(`**ما بعد السنة 4:** بعد إتمام ${career.educationLevel}، اسعَ للحصول على شهادات أو تدريب متخصص في المجالات الناشئة ضمن ${career.category} للحفاظ على تنافسيتك`);
  } else {
    steps.push(`**This Month:** Research ${title} careers by watching day-in-the-life videos and reading professional profiles to understand daily responsibilities`);
    steps.push(`**Next 3 Months:** Connect with a ${title} professional for a 20-minute informational interview to learn about their career journey and advice`);

    if (assessment.favoriteSubjects && (assessment.favoriteSubjects as string[]).length > 0) {
      const topSubject = (assessment.favoriteSubjects as string[])[0];
      steps.push(`**Next 6 Months:** Excel in ${topSubject} by seeking advanced projects or competitions to build foundational knowledge for this career`);
    }

    steps.push(`**Next Year:** Start building key skills like ${skills01} through online courses, school clubs, or personal projects`);
    steps.push(`**Years 2-3:** Gain hands-on experience through internships, volunteer work, or part-time opportunities in ${career.category} to build your resume and network`);
    steps.push(`**Year 3-4:** Research and apply to universities offering strong programs in ${career.category}, focusing on institutions with industry connections and practical training`);
    steps.push(`**Beyond Year 4:** After completing ${career.educationLevel}, pursue certifications or specialized training in emerging areas within ${career.category} to stay competitive`);
  }

  return steps;
}
